---
sidebar: sidebar 
permalink: oracle/oracle-host-config-windows.html 
keywords: oracle, database, ontap, windows 
summary: Oracle Datenbanken mit Microsoft Windows 
searchtitle: Oracle Datenbanken mit Microsoft Windows 
---
= Microsoft Windows
:allow-uri-read: 


[role="lead"]
Konfigurationsthemen für Oracle Database unter Microsoft Windows mit ONTAP..



== NFS

Oracle unterstützt den Einsatz von Microsoft Windows mit dem direkten NFS-Client. Diese Funktion eröffnet neue Möglichkeiten für das Management von NFS. Hierzu zählen beispielsweise die Möglichkeit, Dateien über verschiedene Umgebungen hinweg anzuzeigen, Volumes dynamisch zu skalieren und das kostengünstigere IP-Protokoll zu nutzen. Informationen zur Installation und Konfiguration einer Datenbank unter Microsoft Windows unter Verwendung von DNFS finden Sie in der offiziellen Oracle-Dokumentation. Es gibt keine speziellen Best Practices.



== San

Stellen Sie für eine optimale Komprimierungseffizienz sicher, dass das NTFS-Dateisystem eine Zuweisungseinheit mit 8 KB oder mehr verwendet. Die Verwendung einer 4-KB-Zuweisungseinheit, die im Allgemeinen die Standardeinstellung ist, wirkt sich negativ auf die Komprimierungseffizienz aus.
