---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM, oracle, ASA r2 
summary: LUN-Ausrichtung mit Oracle-Datenbanken auf ASA r2 
searchtitle: LUN-Ausrichtung für Oracle-Datenbank-E/A mit ASA r2 
---
= LUN-Ausrichtung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
LUN-Ausrichtung bezieht sich auf die I/O-Optimierung in Bezug auf das zugrunde liegende Filesystem-Layout.

ASA r2-Systeme nutzen die gleiche ONTAP Architektur wie AFF/ FAS , jedoch mit einem vereinfachten Konfigurationsmodell. ASA r2-Systeme verwenden Storage Availability Zones (SAZ) anstelle von Aggregaten, aber die Ausrichtungsprinzipien bleiben gleich, da ONTAP das Blocklayout plattformübergreifend konsistent verwaltet. Beachten Sie jedoch folgende ASA-spezifische Punkte:

* ASA r2-Systeme bieten aktiv-aktiv symmetrische Pfade für alle LUNs, wodurch Probleme mit Pfadasymmetrien während der Ausrichtung beseitigt werden.
* Speichereinheiten (LUNs) werden standardmäßig Thin-Provisioning-fähig gemacht; die Ausrichtung ändert nichts an diesem Verhalten.
* Snapshot-Reservierung und automatische Snapshot-Löschung können bei der LUN-Erstellung konfiguriert werden (ONTAP 9.18.1 und höher).


Auf einem ONTAP-System wird der Storage in 4-KB-Einheiten organisiert. Ein Datenbank- oder Filesystem-8-KB-Block sollte exakt zwei 4-KB-Blöcken zugeordnet werden. Wenn ein Fehler in der LUN-Konfiguration die Ausrichtung um 1 KB in beide Richtungen verschiebt, wäre jeder 8-KB-Block auf drei verschiedenen 4-KB-Storage-Blöcken vorhanden anstatt auf zwei. Diese Anordnung würde zu einer erhöhten Latenz führen und dazu führen, dass zusätzliche I/O-Vorgänge innerhalb des Speichersystems ausgeführt werden.

Die Ausrichtung wirkt sich auch auf LVM-Architekturen aus. Wenn ein physisches Volume innerhalb einer logischen Volume-Gruppe auf dem gesamten Laufwerk definiert wird (es werden keine Partitionen erstellt), wird der erste 4-KB-Block auf der LUN auf den ersten 4-KB-Block im Storage-System ausgerichtet. Dies ist eine korrekte Ausrichtung. Probleme ergeben sich bei Partitionen, da sie den Startort verschieben, an dem das Betriebssystem die LUN verwendet. Solange der Offset in ganzen 4-KB-Einheiten verschoben wird, ist die LUN ausgerichtet.

Erstellen Sie in Linux-Umgebungen logische Volume-Gruppen auf dem gesamten Laufwerkgerät. Wenn eine Partition erforderlich ist, überprüfen Sie die Ausrichtung, indem Sie ausführen `fdisk -u` und überprüfen, ob der Anfang jeder Partition ein Vielfaches von acht ist. Dies bedeutet, dass die Partition bei einem Vielfachen von acht 512-Byte-Sektoren beginnt, was 4 KB ist.

Siehe auch die Diskussion über die Ausrichtung der Kompressionsblöcke im Abschnitt link:oracle-ontap-config-efficiency.html["Effizienz"]. Jedes Layout, das an 8-KB-Komprimierungsblockgrenzen ausgerichtet ist, ist auch an 4-KB-Grenzen ausgerichtet.



== Warnungen wegen Falschausrichtung

Die Datenbank-Wiederherstellungs-/Transaktionsprotokollierung erzeugt normalerweise nicht ausgerichtete I/O-Vorgänge, die irreführende Warnungen zu falsch ausgerichteten LUNs auf ONTAP verursachen können.

Die Protokollierung führt einen sequenziellen Schreibvorgang der Protokolldatei mit unterschiedlich großen Schreibvorgängen durch. Ein Protokollschreibvorgang, der sich nicht an 4-KB-Grenzen ausrichtet, verursacht normalerweise keine Performance-Probleme, da der nächste Protokollschreibvorgang den Block abgeschlossen hat. Das Ergebnis: ONTAP ist in der Lage, fast alle Schreibvorgänge als komplette 4-KB-Blöcke zu verarbeiten, obwohl die Daten in einigen 4-KB-Blöcken in zwei separaten Operationen geschrieben wurden.

Überprüfen Sie die Ausrichtung mithilfe von Hilfsprogrammen wie z. B. `sio` oder `dd` das E/A mit einer definierten Blockgröße erzeugen kann. Die I/O-Ausrichtungsstatistiken des Speichersystems können mit folgendem angezeigt werden: `stats` Befehl. Sehen link:../notes/wafl_alignment_verification.html["Überprüfung der WAFL-Ausrichtung"] für weitere Informationen.

Die Ausrichtung in Solaris-Umgebungen ist komplizierter. Siehe http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["ONTAP SAN-Host-Konfiguration"^] Finden Sie weitere Informationen.

[CAUTION]
====
Achten Sie in Solaris x86-Umgebungen besonders auf die richtige Ausrichtung, da die meisten Konfigurationen mehrere Ebenen von Partitionen haben. Solaris x86-Partitionsschichten befinden sich in der Regel oben auf einer Standard-Master-Bootdatensammelpartitionstabelle.

====
Weitere bewährte Vorgehensweisen:

* Überprüfen Sie die Firmware- und Betriebssystemeinstellungen des HBA anhand des NetApp Interoperability Matrix Tool (IMT).
* Verwenden Sie die sanlun-Dienstprogramme, um die Integrität und Ausrichtung des Pfades zu überprüfen.
* Stellen Sie bei Oracle ASM und LVM sicher, dass die Konfigurationsdateien (/etc/lvm/lvm.conf, /etc/sysconfig/oracleasm) korrekt eingestellt sind, um Ausrichtungsprobleme zu vermeiden.

