---
sidebar: sidebar 
permalink: oracle/oracle-host-config-windows.html 
keywords: oracle, database, ontap, windows 
summary: Oracle Datenbanken mit Microsoft Windows 
searchtitle: Oracle Datenbanken mit Microsoft Windows 
---
= Microsoft Windows
:allow-uri-read: 


[role="lead"]
Konfigurationsthemen für Oracle Database unter Microsoft Windows mit ONTAP..



[[nfs]]
== NFS

Oracle unterstützt die Verwendung von Microsoft Windows mit dem direkten NFS-Client. Diese Funktion bietet einen Weg zu den Managementvorteilen von NFS, einschließlich der Möglichkeit, Dateien über verschiedene Umgebungen hinweg anzuzeigen, NFS-Volumes dynamisch zu vergrößern und ein kostengünstigeres IP-Protokoll zu nutzen. Siehe die offizielle Oracle-Dokumentation für Informationen zur Installation und Konfiguration einer Datenbank unter Microsoft Windows mit DNFS. Es gibt keine speziellen Best Practices.



[[san]]
== San

Stellen Sie für eine optimale Komprimierungseffizienz sicher, dass das NTFS-Dateisystem eine Zuweisungseinheit mit 8 KB oder mehr verwendet. Die Verwendung einer 4-KB-Zuweisungseinheit, die im Allgemeinen die Standardeinstellung ist, wirkt sich negativ auf die Komprimierungseffizienz aus.
