---
sidebar: sidebar 
permalink: oracle/oracle-dr-mcc-failover.html 
keywords: Metrocluster, mcc, MCC-IP 
summary: Oracle mit MetroCluster 
---
= Oracle Failover mit MetroCluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Verwendung von MetroCluster trägt nicht notwendigerweise zur Ergänzung oder Änderung von Best Practices für den Betrieb von Enterprise-Applikationen und Datenbanken bei.

Die üblichen Best Practices gelten weiterhin, und wenn Ihre Bedürfnisse nur RPO=0 Datensicherung erfordern, wird diese Anforderung mit MetroCluster erfüllt. Die meisten Kunden verwenden MetroCluster jedoch nicht nur für die RPO=0-Datensicherung, sondern auch zur Verbesserung der RTO in Notfallszenarien sowie zur Gewährleistung eines transparenten Failovers im Rahmen der Wartungsarbeiten an den Standorten.



== Failover mit einem vorkonfigurierten Betriebssystem

SyncMirror liefert eine synchrone Kopie der Daten am Disaster Recovery-Standort. Um diese Daten verfügbar zu machen, sind jedoch ein Betriebssystem und die zugehörigen Applikationen erforderlich. Eine grundlegende Automatisierung kann die Failover-Zeit der gesamten Umgebung deutlich verbessern. Clusterware-Produkte wie Oracle RAC, Veritas Cluster Server (VCS) oder VMware HA werden oft verwendet, um standortübergreifend ein Cluster zu erstellen. In vielen Fällen kann der Failover-Prozess mit einfachen Skripten vorangetrieben werden.

Wenn die primären Knoten verloren gehen, ist die Clusterware (oder Skripte) so konfiguriert, dass die Anwendungen am alternativen Standort online geschaltet werden. Eine Möglichkeit besteht darin, Standby-Server zu erstellen, die für die NFS- oder SAN-Ressourcen, aus denen die Applikation besteht, vorkonfiguriert sind. Wenn der primäre Standort ausfällt, führt die Clusterware- oder skriptbasierte Alternative eine Abfolge von Aktionen durch, die der folgenden ähneln:

. Erzwingen einer MetroCluster-Umschaltung
. Durchführen der Erkennung von FC-LUNs (nur SAN)
. Mounten von Dateisystemen
. Starten der Anwendung


Die primäre Anforderung dieses Ansatzes ist ein Betriebssystem, das am Remote Standort ausgeführt wird. Es muss mit Applikations-Binärdateien vorkonfiguriert werden. Das bedeutet auch, dass Aufgaben wie Patching am primären Standort und Standby-Standort durchgeführt werden müssen. Alternativ können die Binärdateien der Applikation auf den Remote-Standort gespiegelt und gemountet werden, wenn ein Notfall gemeldet wird.

Die eigentliche Aktivierung ist einfach. Befehle wie die LUN-Erkennung erfordern nur einige wenige Befehle pro FC-Port. Das Mounten des Filesystems ist nichts anderes als ein `mount` Befehl, und sowohl Datenbanken als auch ASM können über die CLI mit einem einzigen Befehl gestartet und gestoppt werden. Wenn die Volumes und Dateisysteme vor dem Switchover nicht am Disaster-Recovery-Standort verwendet werden, müssen Sie sie nicht festlegen `dr-force- nvfail` Auf Volumes.



== Failover mit einem virtualisierten Betriebssystem

Der Failover von Datenbankumgebungen kann auf das Betriebssystem selbst erweitert werden. In der Theorie kann dieses Failover mit Boot-LUNs durchgeführt werden, meistens erfolgt es jedoch mit einem virtualisierten Betriebssystem. Das Verfahren ähnelt den folgenden Schritten:

. Erzwingen einer MetroCluster-Umschaltung
. Mounten der Datenspeicher, die die virtuellen Maschinen des Datenbankservers hosten
. Starten der virtuellen Maschinen
. Manuelles Starten von Datenbanken oder Konfigurieren der virtuellen Maschinen, um die Datenbanken automatisch zu starten


Beispielsweise kann ein ESX Cluster mehrere Standorte umfassen. Bei einem Notfall können die Virtual Machines nach dem Switchover am Disaster Recovery-Standort online geschaltet werden. Solange die Datastores, die die virtualisierten Datenbankserver hosten, zum Zeitpunkt des Ausfalls nicht verwendet werden, ist keine Einstellung erforderlich `dr-force- nvfail` Auf zugeordneten Volumes.
