---
sidebar: sidebar 
permalink: oracle/oracle-dr-smbc-rac.html 
keywords: oracle, smbc, sm-bc, RAC 
summary: Oracle RAC mit aktiver SnapMirror Synchronisierung 
---
= Oracle RAC mit aktiver SnapMirror Synchronisierung
:allow-uri-read: 


[role="lead"]
SnapMirror Active Sync bietet granulare Kontrolle über die Replizierung von Datensätzen für Zwecke wie Lastausgleich oder individuellen Applikations-Failover. Die Gesamtarchitektur sieht aus wie ein erweiterter RAC-Cluster, einige Datenbanken sind jedoch bestimmten Standorten zugewiesen und die Gesamtlast ist verteilt.

Sie könnten beispielsweise einen Oracle RAC-Cluster erstellen, der sechs einzelne Datenbanken hostet. Der Storage für drei der Datenbanken würde hauptsächlich auf Standort A und der Storage für die anderen drei Datenbanken auf Standort B gehostet werden Diese Konfiguration sorgt durch die Minimierung des standortübergreifenden Datenverkehrs für eine bestmögliche Performance. Außerdem sollten Applikationen so konfiguriert werden, dass sie die im Storage-System lokalen Datenbankinstanzen mit aktiven Pfaden verwenden. Dies minimiert den RAC Interconnect-Datenverkehr. Schließlich stellt dieses Gesamtdesign sicher, dass alle Rechenressourcen gleichmäßig genutzt werden. Bei sich ändernden Workloads können Datenbanken selektiv standortübergreifend und hin- und herausgefallen sein, um ein gleichmäßiges Laden zu gewährleisten.

Anders als Granularität sind die grundlegenden Prinzipien und Optionen für Oracle RAC mit SnapMirror Active syncare identisch mit denen für link:../metrocluster/mcc-rac.html["Oracle RAC auf MetroCluster"]
