---
sidebar: sidebar 
permalink: oracle/oracle-dp-consistency-group-backup.html 
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles 
summary: Backups von Konsistenzgruppen für Oracle-Datenbanken auf ONTAP 
searchtitle: Backups der Konsistenzgruppe in der Oracle Datenbank 
---
= Backups von Konsistenzgruppen
:allow-uri-read: 


[role="lead"]
Für eine möglichst einfache Datensicherung platzieren Sie einfach die gesamte Oracle Datenbank in einem einzigen ONTAP Volume, einer LUN oder einem NVMe-Namespace.

Das Sichern von Datenbankdateien, Archivprotokollen, Wiederherstellungsprotokollen und Kontrolldateien mit einem einzelnen Snapshot ist eine gültige Methode für Backup, Wiederherstellung und Replikation. Der RPO ist jedoch auf den Zeitpunkt des Backups selbst beschränkt. Es ist geeignet für einen RPO von einer Stunde oder mehr. Wenn sich eine Datenbank über AFF Volumes oder ASA Speichereinheiten erstreckt, sind Konsistenzgruppen erforderlich, die mit einem der zuvor beschriebenen Tools erstellt werden.

Als Beispiel kann die gesamte Datenbank in einem einzigen AFF Volume mit folgendem Snapshot-Zeitplan liegen:

* 72 stündliche Snapshots
* 30 nächtliche Schnappschüsse
* 12 monatliche Snapshots


Dies ermöglicht einen RPO von einer Stunde über den rollierenden Zeitraum der vorangegangenen 72 Stunden, zuzüglich zusätzlicher nächtlicher und monatlicher Backups. Mehrere Datenbanken oder Anwendungsdateien können auch in einem einzelnen Volume oder einem Satz von Konsistenzgruppen-Snapshots enthalten sein, um konsistente Backups in einer größeren Umgebung zu gewährleisten.
