---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: Schnelle Oracle Datenbank-Recovery mit Snapshots 
searchtitle: Schnelle Oracle Datenbank-Recovery mit Snapshots 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die schnelle Datenwiederherstellung in ONTAP aus einem Snapshot wird durch die NetApp SnapRestore Technologie ermöglicht, die es erlaubt, den Zustand eines AFF-Volumes oder einer ASA LUN sofort wiederherzustellen.

Wenn ein kritischer Datensatz nicht verfügbar ist, laufen die geschäftskritischen Prozesse ab. Tapes können beschädigt werden und selbst Restores aus festplattenbasierten Backups können die Übertragung über das Netzwerk verlangsamen. SnapRestore vermeidet diese Probleme durch eine nahezu sofortige Wiederherstellung der Datensätze. Selbst Datenbanken im Petabyte-Bereich lassen sich in wenigen Minuten vollständig wiederherstellen.

Obwohl die Basistechnologie auf AFF und ASA Plattformen dieselbe ist, werden sie etwas unterschiedlich eingesetzt.



[[aff-overview]]
== AFF-Übersicht

Es gibt zwei Formen von SnapRestore auf einem AFF System – dateibasiert und volumenbasiert:

* Einzelne AFF Dateien, LUNs und Namensräume sowie einzelne ASA LUNs und Namensräume können in Sekunden wiederhergestellt werden, egal ob es sich um eine 2TB LUN oder eine 4KB Datei handelt.
* Der gesamte Inhalt eines AFF-Volumes kann in Sekundenschnelle wiederhergestellt werden, egal ob es sich um 10GB oder 100TB Daten handelt.


Der Grund, warum SnapRestore so schnell und effizient funktioniert, liegt in der Natur eines Snapshots, der im Wesentlichen eine parallele, schreibgeschützte Ansicht des Inhalts eines Volumes, einer LUN oder eines Namespace zu einem bestimmten Zeitpunkt darstellt. Die aktiven Blöcke sind die realen Blöcke, die geändert werden können, während der Snapshot eine schreibgeschützte Ansicht des Zustands der Blöcke ist, aus denen die Dateien und LUNs zum Zeitpunkt der Snapshot-Erstellung bestehen.

ONTAP erlaubt nur Lesezugriff auf Snapshot-Daten, aber die Daten können mit SnapRestore reaktiviert werden. Der Snapshot wird als Lese-/Schreibansicht der Daten wieder aktiviert, wodurch die Daten in ihren vorherigen Zustand zurückversetzt werden. SnapRestore kann auf Volume-, Datei-, LUN- oder Namespace-Ebene arbeiten. Die Technologie ist im Wesentlichen dieselbe, mit einigen geringfügigen Unterschieden im Verhalten.



[[aff-volume-snaprestore]]
=== AFF Volume SnapRestore

Die volumenbasierte SnapRestore stellt den Inhalt eines gesamten Volumes auf einen früheren Zustand zurück. Dieser Vorgang erfordert keine Datenverschiebung, wodurch der Wiederherstellungsprozess im Wesentlichen sofort erfolgt, obwohl die API- oder CLI-Operation einige Sekunden zur Verarbeitung benötigen kann. Die Wiederherstellung von 1GB Daten ist nicht komplizierter oder zeitaufwändiger als die Wiederherstellung von 1PB Daten. Diese Fähigkeit ist der Hauptgrund, warum viele Unternehmenskunden auf ONTAP Storage-Systeme migrieren. Sie ermöglicht eine RTO im Sekundenbereich selbst für die größten Datensätze.

Ein Nachteil von Volume-basierten SnapRestore ist die Tatsache, dass Änderungen innerhalb eines Volumes im Laufe der Zeit kumuliert werden. Daher sind jeder Snapshot und die Daten der aktiven Datei von den bis zu diesem Zeitpunkt vorgenommenen Änderungen abhängig. Das Zurücksetzen eines Volumes in einen früheren Zustand bedeutet, dass alle nachfolgenden Änderungen, die an den Daten vorgenommen wurden, verworfen werden. Weniger offensichtlich ist jedoch, dass dies nachträglich erstellte Snapshots einschließt. Das ist nicht immer wünschenswert.

Beispielsweise kann in einem SLA für die Datenaufbewahrung eine nächtliche Sicherung von 30 Tagen festgelegt werden. Wenn ein Datensatz auf einen vor fünf Tagen mit Datenträger SnapRestore erstellten Snapshot wiederhergestellt wird, werden alle in den letzten fünf Tagen erstellten Snapshots verworfen und dies verstößt gegen den SLA.

Es gibt eine Reihe von Optionen, um diese Einschränkung zu beheben:

. Daten können von einem früheren Snapshot kopiert werden, anstatt eine SnapRestore des gesamten Volumes durchzuführen. Diese Methode eignet sich am besten für kleinere Datensätze.
. Ein Snapshot kann geklont und nicht wiederhergestellt werden. Die Einschränkung dieses Ansatzes besteht darin, dass der Quell-Snapshot eine Abhängigkeit des Klons ist. Daher kann sie nur gelöscht oder in ein unabhängiges Volume aufgesplittet werden.
. Verwendung von dateibasiertem SnapRestore.




[[aff-file-snaprestore]]
=== AFF Datei SnapRestore

Die dateibasierte SnapRestore ist ein detaillierteres, snapshotbasiertes Wiederherstellungsverfahren, das bei AFF-Volumes zum Einsatz kommt. Anstatt den Zustand eines gesamten Volumes wiederherzustellen, wird der Zustand einer einzelnen Datei, LUN oder eines Namespaces zurückgesetzt. Es müssen keine Snapshots gelöscht werden, noch entsteht durch diesen Vorgang eine Abhängigkeit von einem vorherigen Snapshot. Die Datei oder LUN steht im aktiven Volume sofort zur Verfügung.

Für die SnapRestore-Wiederherstellung einer Datei oder LUN ist keine Datenverschiebung erforderlich. Allerdings sind einige interne Metadatenaktualisierungen erforderlich, um dem Umstand Rechnung zu tragen, dass die zugrunde liegenden Blöcke der wiederhergestellten Daten nun sowohl in einem Snapshot als auch im aktiven Volume vorhanden sind. Es sollte keine Auswirkungen auf die Leistung geben, jedoch blockiert dieser Prozess die Erstellung von Snapshots, bis er abgeschlossen ist. Die Verarbeitungsrate beträgt etwa 5 GB/s (18 TB/Stunde) basierend auf der Gesamtgröße der wiederhergestellten Dateien.



[[asa-lunnamespace-restoration]]
== ASA LUN-/Namensraum-Wiederherstellung

Die Wiederherstellung von Daten auf ASA ist ähnlich wie bei AFF SnapRestore. Die Daten werden einfach auf einen früheren Zustand zurückgesetzt. Der Vorgang ist nahezu sofort abgeschlossen und erfordert keine Datenverschiebung. Es gelten jedoch dieselben Einschränkungen, einschließlich der Anforderung, dass die Wiederherstellung eines Snapshots zum Löschen nachfolgend gelöschter Snapshots führt. Wenn dies problematisch ist, gibt es zwei Optionen. Erstens kann eine LUN/ein Namespace aus einem früheren Snapshot geklont werden, während das Quellvolume unverändert bleibt. Dies ist ein sofortiger und speichereffizienter Prozess. Im Wesentlichen wird eine Lese-/Schreibkopie des schreibgeschützten Zeigers auf die Blöcke in einem Snapshot erstellt. Eine zweite Option ist über die REST-API möglich, die dieselbe Einzeldatei SnapRestore Logik wie bei AFF Systemen verwendet. Das Ergebnis ist eine sofortige Wiederherstellung einer LUN/eines Namespace mithilfe der Daten aus einem Snapshot, wobei alle Snapshots erhalten bleiben.
