---
sidebar: sidebar 
permalink: oracle/oracle-virtualization-introduction.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: Einführung in die Datenbankvirtualisierung 
---
= Einheitliche
:allow-uri-read: 


[role="lead"]
Die Virtualisierung von Datenbanken mit VMware ESX, Oracle OVM oder KVM wird für NetApp-Kunden, die sich für die Virtualisierung selbst für ihre geschäftskritischsten Datenbanken entschieden haben, immer häufiger eingesetzt.

In den Support-Richtlinien für Virtualisierung gibt es viele falsche Annahmen, insbesondere für VMware Produkte. Tatsächlich ist es nicht ungewöhnlich zu hören, dass Oracle keine Virtualisierung unterstützt. Diese Vorstellung ist falsch und führt zu verpassten Virtualisierungsmöglichkeiten. Oracle Doc ID 249212.1 behandelt bekannte Probleme in einer Oracle-Umgebung und gibt auch die Unterstützung für RAC an.

Ein Kunde mit einem Oracle unbekannten Problem wird möglicherweise gebeten, das Problem auf physischer Hardware zu reproduzieren. Ein Oracle Kunde, der eine brandneue Version eines Produkts ausführt, möchte möglicherweise wegen der Möglichkeit einer neuen Fehlererkennung keine Virtualisierung verwenden. Für Virtualisierungskunden, die allgemein verfügbare Produktversionen verwenden, war diese Situation jedoch in der Praxis kein Problem.



== Storage-Präsentation

Kunden, die eine Virtualisierung ihrer Datenbanken in Erwägung ziehen, sollten ihre Storage-Entscheidungen basierend auf ihren Geschäftsanforderungen treffen. Dies ist zwar eine allgemein zutreffende Aussage für alle IT-Entscheidungen, ist jedoch besonders für die Virtualisierung wichtig, da die Größe und der Umfang der Projekte erheblich variieren.

Es gibt vier grundlegende Optionen für die Storage-Präsentation:

* Vom iSCSI-Initiator gemanagte iSCSI-LUNs auf der VM, nicht der Hypervisor
* NFS-Dateisysteme, die von der VM gemountet werden, kein Virtual Machine Disk (VMDK)
* Hypervisor-Datastores


Vermeiden Sie in der Regel die Verwendung von Datastores für Oracle-Dateien. Diese Empfehlung hat viele Gründe:

* *Transparenz.* Wenn eine VM Eigentümer ihrer Dateisysteme ist, ist es einfacher für einen Datenbank-Administrator oder einen Systemadministrator, die Quelle der Dateisysteme für ihre Daten zu identifizieren.
* *Performance.* Tests haben gezeigt, dass es einen Performance-Effekt gibt, wenn alle I/O über einen Hypervisor-Datastore geleitet werden.
* *Verwaltbarkeit.* Wenn eine VM Eigentümer ihrer Dateisysteme ist, wirkt sich die Verwendung oder Nichtnutzung einer Hypervisor-Schicht auf die Verwaltbarkeit aus. Die gleichen Verfahren für die Bereitstellung, das Monitoring, die Datensicherung usw. können über den gesamten Bestand hinweg eingesetzt werden, einschließlich sowohl virtualisierter als auch nicht virtualisierter Umgebungen.
* *Stabilität und Fehlerbehebung.* Wenn eine VM über ihre Dateisysteme verfügt, sind die Bereitstellung einer guten, stabilen Leistung und Problembehandlung viel einfacher, da der gesamte Speicher-Stack auf der VM vorhanden ist. Die einzige Rolle des Hypervisors besteht darin, FC- oder IP-Frames zu transportieren. Wenn ein Datastore in einer Konfiguration enthalten ist, wird die Konfiguration durch die Einführung eines weiteren Satzes von Timeouts, Parametern, Protokolldateien und potenziellen Bugs erschwert.
* *Portabilität.* Wenn eine VM Eigentümer ihrer Dateisysteme ist, wird der Prozess des Verschiebens einer Oracle-Umgebung viel einfacher. Dateisysteme können problemlos zwischen virtualisierten und nicht virtualisierten Gastsystemen verschoben werden.
* *Vendor Lock-in.* Nachdem die Daten in einem Datastore platziert wurden, wird es sehr schwierig, einen anderen Hypervisor zu verwenden oder die Daten aus der virtualisierten Umgebung zu nehmen.
* *Snapshot-Aktivierung.* in manchen Fällen können Backups in einer virtualisierten Umgebung wegen der relativ begrenzten Bandbreite zum Problem werden. So kann beispielsweise ein 10-GbE-Trunk mit vier Ports ausreichen, um die täglichen Performance-Anforderungen vieler virtualisierter Datenbanken zu unterstützen. Ein solcher Trunk wäre jedoch nicht ausreichend, um Backups mit RMAN oder anderen Backup-Produkten durchzuführen, die ein Streaming einer vollständigen Kopie der Daten erfordern.
+
Durch die Verwendung von Filesystemen, die sich im Besitz von VMs befinden, können Snapshot-basierte Backups und Restores einfacher genutzt werden. Ein Dateisystem, das sich im Besitz von VMs befindet, lädt die Durchführung von Backups auf das Storage-System. Die Hypervisor-Konfiguration muss nicht allein zur Unterstützung der Bandbreiten- und CPU-Anforderungen im Backup-Fenster überdimensioniert werden.




TIP: *NetApp empfiehlt* die Vermeidung der Platzierung von Oracle-Daten auf einem Datastore, um optimale Performance und Verwaltbarkeit zu erreichen. Verwenden Sie vom Gast gemanagte Dateisysteme wie NFS- oder iSCSI-Dateisysteme oder mit RDMs.



== Paravirtualisierte Treiber

Für eine optimale Leistung ist die Verwendung paravirtualisierter Netzwerktreiber von entscheidender Bedeutung. Wenn ein Datastore verwendet wird, ist ein paravirtualisierter SCSI-Treiber erforderlich. Ein paravirtualisierter Gerätetreiber ermöglicht es einem Gast, sich tiefer in den Hypervisor zu integrieren, im Gegensatz zu einem emulierten Treiber, bei dem der Hypervisor mehr CPU-Zeit damit verbringt, das Verhalten physischer Hardware nachzuahmen.

Die Performance der meisten Datenbanken wird durch Storage eingeschränkt. Daher fällt die zusätzliche Latenz, die durch ein Netzwerk oder einen SCSI-Treiber entsteht, besonders auf. Der NetApp Kundensupport ist auf viele Leistungsbeschwerden gestoßen, die durch die Installation paravirtualisierter Treiber behoben wurden. Bei einem Machbarkeitsnachweis für Kunden zeigten Datenbanken eine bessere Performance unter ESX als bei derselben Hardware, die wie beim Bare Metal lief. Die Tests waren sehr I/O-intensiv und der Performance-Unterschied wurde durch die Verwendung der paravirtualisierten ESX Netzwerktreiber zugeschrieben.


TIP: *NetApp empfiehlt* immer paravirtualisierte Netzwerktreiber und SCSI-Treiber zu verwenden.



== RAM überschreiben

Das Überschreiben von RAM bedeutet, mehr virtualisierten RAM auf verschiedenen Hosts zu konfigurieren, als auf der physischen Hardware vorhanden ist. Dies kann zu unerwarteten Leistungsproblemen führen. Bei der Virtualisierung einer Datenbank dürfen die zugrunde liegenden Blöcke des Oracle SGA nicht durch den Hypervisor in den Storage getauscht werden. Dies führt zu äußerst instabilen Performance-Ergebnissen.


TIP: *NetApp empfiehlt*, einen Hypervisor nicht so zu konfigurieren, dass Oracle SGA-Blöcke ausgetauscht werden können.
