---
sidebar: sidebar 
permalink: oracle/oracle-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM 
summary: LUN-Ausrichtung mit Oracle Datenbanken 
searchtitle: LUN-Ausrichtung für Oracle Database I/O 
---
= LUN-Ausrichtung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
LUN-Ausrichtung bezieht sich auf die I/O-Optimierung in Bezug auf das zugrunde liegende Filesystem-Layout.

Nicht aufgelöste Direktive in <stdin> - include::lun-Alignment.adoc[]

Siehe auch die Diskussion über die Ausrichtung der Kompressionsblöcke im Abschnitt link:oracle-ontap-config-efficiency.html["Effizienz"]. Jedes Layout, das an 8-KB-Komprimierungsblockgrenzen ausgerichtet ist, ist auch an 4-KB-Grenzen ausgerichtet.



== Warnungen wegen Falschausrichtung

Ungelöste Direktive in <stdin> - include::Database-falignment-warnungen.adoc[]

Die Ausrichtung in Solaris-Umgebungen ist komplizierter. Siehe http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["ONTAP SAN-Host-Konfiguration"^] Finden Sie weitere Informationen.

|===
| Achtung 


| Achten Sie in Solaris x86-Umgebungen besonders auf die richtige Ausrichtung, da die meisten Konfigurationen mehrere Ebenen von Partitionen haben. Solaris x86-Partitionsschichten befinden sich in der Regel oben auf einer Standard-Master-Bootdatensammelpartitionstabelle. 
|===