---
sidebar: sidebar 
permalink: oracle/oracle-dp-online-backup.html 
keywords: oracle, data protection, hot backup 
summary: Snapshot-basierte Backups und Recovery für Oracle-Datenbanken 
searchtitle: Online-Backups von Oracle Datenbanken 
---
= Online-Backups
:allow-uri-read: 


[role="lead"]
Zwei Datensätze sind erforderlich, um eine Oracle Datenbank im Backup-Modus zu schützen und wiederherzustellen. Beachten Sie, dass dies nicht die einzige Oracle-Backup-Option ist, aber es ist die häufigste.

* Ein Snapshot der Datendateien im Backup-Modus
* Die Archivprotokolle, die erstellt wurden, während sich die Datendateien im Backup-Modus befanden


Wenn eine vollständige Recovery einschließlich aller festgeschriebenen Transaktionen notwendig ist, ist ein dritter Artikel erforderlich:

* Ein Satz aktueller Wiederherstellungsprotokolle


Es gibt eine Reihe von Möglichkeiten, die Recovery eines Online-Backups zu fördern. Viele Kunden stellen Snapshots mithilfe der ONTAP CLI wieder her und verwenden dann Oracle RMAN oder sqlplus, um die Recovery abzuschließen. Dies ist besonders bei großen Produktionsumgebungen der Fall, in denen die Wahrscheinlichkeit und Häufigkeit der Wiederherstellung von Datenbanken äußerst gering ist und alle Wiederherstellungsverfahren von einem erfahrenen DBA durchgeführt werden. Für die vollständige Automatisierung verfügen Lösungen wie NetApp SnapCenter über ein Oracle Plug-in mit Befehlszeile und grafischer Benutzeroberfläche.

Einige große Kunden haben einen einfacheren Ansatz verfolgt, indem sie einfache Skripte auf den Hosts konfigurieren, um die Datenbanken zu einem bestimmten Zeitpunkt in den Backup-Modus zu versetzen, um einen geplanten Snapshot vorzubereiten. Planen Sie beispielsweise den Befehl `alter database begin backup` Um 23:58 `alter database end backup` Um 00:02 Uhr, und planen Sie dann Snapshots direkt auf dem Speichersystem um Mitternacht. Das Ergebnis ist eine einfache, hochgradig skalierbare Backup-Strategie, für die keine externe Software oder Lizenzen erforderlich sind.



== Datenlayout

Das einfachste Storage-Layout besteht darin, Datenbankdateien in einem oder mehreren dedizierten Volumes, LUNs oder NVMe-Namespaces zu isolieren. Die Speicherressourcen müssen frei von jeglichen anderen Dateitypen sein. Dies stellt sicher, dass die Datenbankdateien durch einen SnapRestore-Vorgang schnell wiederhergestellt werden können, ohne ein wichtiges Wiederherstellungsprotokoll, eine Kontrolldatei oder ein Archiv-Log zu zerstören.

SAN stellt ähnliche Anforderungen an die Isolation von Datendateien innerhalb dedizierter Ressourcen. Bei einem Betriebssystem wie Microsoft Windows mit AFF Storage kann ein einzelnes Volume mehrere Datendatei-LUNs enthalten, die jeweils ein NTFS-Dateisystem verwenden. Bei anderen Betriebssystemen gibt es in der Regel einen logischen Volume-Manager. Beispielsweise wäre bei Oracle ASM die einfachste Option, die LUNs einer ASM Festplattengruppe auf ein einzelnes Volume zu beschränken, das als Einheit gesichert und wiederhergestellt werden kann. Wenn zusätzliche Volumes aus Performance- oder Kapazitätsmanagement-Gründen erforderlich sind, vereinfacht die Erstellung einer zusätzlichen Festplattengruppe auf dem neuen Volume die Verwaltung.

ASA verfügt nicht über die Abstraktion auf Volume-Ebene, die auf einem AFF-System mehrere LUNs hosten kann. Stattdessen verwendet ASA Konsistenzgruppen. In vielen Fällen kann eine einzelne LUN oder ein NVMe-Namespace die Verwaltungs- und Leistungsanforderungen für eine Datenbank erfüllen. Wenn mehrere LUNs oder Namespaces benötigt werden, können zusätzliche Ressourcen hinzugefügt und als Konsistenzgruppe zusammengefasst werden, die dann den Datenfile-Container bildet.

Wenn diese Richtlinien befolgt werden, können Snapshots direkt auf dem Speichersystem geplant werden.

*Achtung:* Überprüfen Sie, dass der ASM `spfile` Und `passwd` Die Dateien befinden sich nicht in der Festplattengruppe, in der die Datendateien gehostet werden. Dies beeinträchtigt die Fähigkeit, Datendateien und nur Datendateien selektiv wiederherzustellen.



== Verfahren zur lokalen Wiederherstellung – NFS

Dieses Verfahren kann manuell oder über eine Anwendung wie SnapCenter gesteuert werden. Das Grundverfahren ist wie folgt:

. Fahren Sie die Datenbank herunter.
. Stellen Sie die Datendatei-NFS-Volumes auf den Snapshot unmittelbar vor dem gewünschten Wiederherstellungspunkt wieder her.
. Geben Sie Archivprotokolle bis zum gewünschten Punkt wieder.
. Wiederholen Sie die aktuellen Wiederherstellungsprotokolle, wenn eine vollständige Wiederherstellung gewünscht wird.


Bei diesem Verfahren wird davon ausgegangen, dass die gewünschten Archivprotokolle noch im aktiven Dateisystem vorhanden sind. Ist dies nicht der Fall, müssen die Archivprotokolle wiederhergestellt werden oder rman/sqlplus kann zu den Daten im Snapshot-Verzeichnis geleitet werden.

Außerdem können Datendateien bei kleineren Datenbanken von einem Endbenutzer direkt aus wiederhergestellt werden `.snapshot` Verzeichnis ohne die Unterstützung von Automatisierungs-Tools oder Storage-Administratoren, ein auszuführen `snaprestore` Befehl.



== Verfahren zur lokalen Wiederherstellung – SAN

Dieses Verfahren kann manuell oder über eine Anwendung wie SnapCenter gesteuert werden. Das Grundverfahren ist wie folgt:

. Fahren Sie die Datenbank herunter.
. Legen Sie die Festplattengruppe(n), die die Datendateien hosten, still. Die Vorgehensweise hängt vom gewählten Logical Volume Manager ab. Bei ASM muss die Datenträgergruppe demontieren. Bei Linux müssen die Dateisysteme demontiert und die logischen Volumes und Volume-Gruppen deaktiviert werden. Ziel ist es, alle Aktualisierungen auf der Zieldatentengruppe zu stoppen, die wiederhergestellt werden sollen.
. Stellen Sie die LUNs, die die Festplattengruppen der Datendateien hosten, auf den Snapshot unmittelbar vor dem gewünschten Wiederherstellungspunkt wieder her.
. Reaktivieren Sie die neu wiederhergestellten Datenträgergruppen.
. Geben Sie Archivprotokolle bis zum gewünschten Punkt wieder.
. Wiederholen Sie alle Wiederherstellungsprotokolle, wenn eine vollständige Wiederherstellung gewünscht wird.


Dieses Verfahren setzt voraus, dass die gewünschten Archivprotokolle noch im aktiven Dateisystem vorhanden sind. Wenn dies nicht der Fall ist, müssen die Archivprotokolle wiederhergestellt werden, indem die Archivprotokoll-LUNs/Namespaces vollständig offline genommen und eine Wiederherstellung durchgeführt wird (oder indem ein Klon eines vorherigen Snapshots erstellt wird, was aufgrund der Erstellung doppelter UUIDs oder LVM-Namen auf demselben Host schwierig sein kann). Dies ist auch ein Beispiel dafür, wie sinnvoll es ist, Archivprotokolle in dedizierten Speicherressourcen zu speichern. Wenn die Archivprotokolle eine Volume-Gruppe mit Redo-Logs teilen, müssen die Redo-Logs vor der Wiederherstellung des gesamten LUN-Satzes an einen anderen Ort kopiert werden. Dieser Schritt verhindert den Verlust der zuletzt aufgezeichneten Transaktionen.
