---
sidebar: sidebar 
permalink: oracle/oracle-dp-planning.html 
keywords: data protection, DR, snapshots, CG 
summary: Planung der Datensicherung für Oracle Datenbanken 
searchtitle: Planung der Datensicherung für Oracle Datenbanken 
---
= Planung der Datensicherheit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die richtige Datensicherungsarchitektur für Oracle-Datenbanken hängt von den geschäftlichen Anforderungen für die Datenaufbewahrung, Recovery-Fähigkeit und die Toleranz für Unterbrechungen bei verschiedenen Ereignissen ab.

Betrachten Sie beispielsweise die Anzahl der im Umfang enthaltenen Applikationen, Datenbanken und wichtigen Datensätze. Die Entwicklung einer Backup-Strategie für einen einzelnen Datensatz gewährleistet, dass die Compliance mit typischen SLAs relativ unkompliziert ist, da nicht viele Objekte zu managen sind. Je mehr Datensätze es gibt, desto komplizierter wird das Monitoring und Administratoren müssen sich zunehmend mit dem Vermeiden von Backup-Fehlern befassen. Wenn eine Umgebung also die Skalierung von Cloud- und Service-Provider-Umgebungen erreicht, braucht es einen ganz anderen Ansatz.

Die Datensatzgröße wirkt sich auch auf die Strategie aus. Es gibt beispielsweise viele Optionen für Backup und Recovery mit einer Datenbank mit 100 GB, da die Datenmenge so klein ist. Das einfache Kopieren der Daten von Backup-Medien mit herkömmlichen Tools bietet normalerweise eine ausreichende RTO für die Recovery. Eine 100-TB-Datenbank benötigt normalerweise eine komplett andere Strategie, es sei denn, das RTO erlaubt einen mehrtägigen Ausfall. In diesem Fall könnte ein herkömmliches Backup und Recovery auf Basis von Kopien akzeptabel sein.

Schließlich gibt es Faktoren, die nicht dem Backup- und Recovery-Prozess selbst unterliegen. Gibt es zum Beispiel Datenbanken, die kritische Produktionsaktivitäten unterstützen, was das Recovery zu einem seltenen Ereignis macht, das nur von erfahrenen DBAs durchgeführt wird? Sind Datenbanken alternativ Teil einer großen Entwicklungsumgebung, in der häufig ein Recovery erfolgt und von einem IT-Team mit Generalisten gemanagt wird?



[[is-a-snapshot-a-backup]]
== Ist ein Snapshot eine Sicherung?

Ein häufig vorgebrachter Einwand gegen die Verwendung von Snapshots als Datensicherungsstrategie ist die Tatsache, dass sich die „echten“ Daten und die Snapshot-Daten auf denselben Laufwerken befinden. Der Verlust dieser Laufwerke würde sowohl zum Verlust der Primärdaten als auch des Backups führen.

Das ist ein berechtigte Anliegen. Lokale Snapshots werden für tägliche Backup- und Recovery-Anforderungen verwendet, in dieser Hinsicht ist der Snapshot ein Backup. Beinahe 99 % aller Recovery-Szenarien in NetApp Umgebungen basieren auf Snapshots, um selbst die anspruchsvollsten RTO-Anforderungen zu erfüllen.

Lokale Snapshots sollten jedoch nie die einzige Backup-Strategie sein. Aus diesem Grund bietet NetApp Technologien wie SnapMirror Replizierung, mit denen Snapshots schnell und effizient auf einen unabhängigen Laufwerkssatz repliziert werden können. In einer richtig konzipierten Lösung mit Snapshots und Snapshot-Replikation kann die Verwendung von Tapes auf ein vierteljährliches Archiv minimiert oder ganz eliminiert werden.



[[crash-consistent-backups]]
== Absturzkonsistente Backups

Ein absturzkonsistenter Backup beinhaltet das Erfassen des Zustands eines Datasets (oder mehrerer Datasets) zu einem einzigen atomaren Zeitpunkt. Als Beispiel für eine Datenbank umfasst dies alle Datenbankkomponenten wie Datendateien, Protokolldateien und andere Dateien, die direkt mit der Datenbank verbunden sind. Dies funktioniert mit nahezu allen relationalen Datenbankprodukten, einschließlich Oracle RDBMS, Microsoft SQL Server, SAP HANA, PostgreSQL, MySQL und MariaDB. Der Schutz einer VMware-Konfiguration mit einem Konsistenzgruppen-Backup wäre ähnlich – es werden alle Datastores und gegebenenfalls die ESX-Boot-LUNs zu einem einzigen atomaren Zeitpunkt erfasst.

Die Erstellung eines solchen Backups simuliert im Wesentlichen einen Absturz, weshalb solche Backups als absturzkonsistente Backups bezeichnet werden. Manchmal bestehen Bedenken hinsichtlich der Unterstützung von Recovery-Szenarien, aber es ist wichtig zu verstehen, dass in der Regel kein Recovery-Verfahren erforderlich ist. Wenn die Anwendung nach dem Wiederherstellen eines Konsistenzgruppen-Backups startet, führt sie die üblichen Protokollwiederherstellungsprozesse, Dateisystem-Journal-Replays und andere Aufgaben durch, um alle zum Zeitpunkt des Backups laufenden I/O-Vorgänge erneut auszuführen. Die Anwendung startet dann wie gewohnt.

Somit können grundsätzlich alle Applikationen geschützt werden, die einem Stromausfall oder Serverabsturz ohne Datenbeschädigung standhalten. Dass dies funktioniert, zeigt sich auch an der großen Zahl an Applikationen, die mit synchronen und asynchronen Spiegelungsprodukten vieler verschiedener Anbieter geschützt sind. Wenn plötzlich am primären Standort ein Notfall eintritt, enthält der Replikatstandort zum Zeitpunkt des Ausfalls ein konsistentes Abbild der ursprünglichen Umgebung. Auch hier ist kein besonderes Recovery-Verfahren erforderlich.

Der RPO für diesen Ansatz ist üblicherweise auf den Zeitpunkt des Backups beschränkt. Als allgemeine Regel gilt, dass der minimale RPO für absturzkonsistenten Backup eine Stunde beträgt. Zum Beispiel sind 48 stündliche Snapshots plus weitere 30 Tage nächtlicher Snapshots sinnvoll und erfordern keine übermäßige Aufbewahrung einer großen Anzahl von Snapshots. Ein RPO von weniger als einer Stunde ist schwieriger zu erreichen und wird nicht empfohlen, ohne vorher NetApp Professional Services zu konsultieren, um die Umgebung, den Umfang und die Anforderungen an den Datenschutz zu verstehen.

Die RTO kann üblicherweise in Sekunden gemessen werden. Wenn eine Anwendung heruntergefahren wird, werden die NFS-Volumes, LUNs oder NVMe-Namespaces wiederhergestellt und die Anwendung neu gestartet.

Am einfachsten lassen sich alle Dateien oder LUNs in einem einzigen AFF Volume oder ASA LUN/Namespace ablegen. Wenn sich ein Datensatz über mehrere Speicherressourcen erstrecken muss, ist eine Konsistenzgruppe erforderlich. Dies kann über den System Manager oder RESTful API-Aufrufe konfiguriert werden, außerdem ist SnapCenter in der Lage, einen einfachen Konsistenzgruppen-Snapshot zu erstellen.



[[replication-and-disaster-recovery-architecture]]
== Architektur für Replizierung und Disaster Recovery

In diesem Abschnitt geht es um die Remote-Datensicherung, bei der Daten zum sicheren externen Storage und zur Disaster Recovery an einen Remote-Standort repliziert werden. Beachten Sie, dass diese Tabellen keine Datensicherung für die synchrone Spiegelung berücksichtigen. Informationen zu dieser Anforderung finden Sie in der NetApp MetroCluster-Dokumentation einschließlich link:oracle-dr-mcc-failover.html["MetroCluster"] und link:oracle-dr-smas-overview.html["SnapMirror Active Sync"]

Das DR RPO wird durch die verfügbare Netzwerkbandbreite und die Gesamtgröße der zu sichernden Daten begrenzt. Nach der Erstellung des ersten Basistransfers basieren die Updates nur auf den geänderten Daten. Dies ist in der Regel ein geringer Prozentsatz des gesamten Datacenter-Platzbedarfs, obwohl es Ausnahmen gibt.

Beispielsweise weist eine 10-TB-Datenbank mit einer wöchentlichen Änderungsrate von 10 % im Schnitt eine Gesamtänderung von 6 GB pro Stunde auf. Mit 10 GB Konnektivität benötigt diese Datenbank etwa sechs Minuten für die Übertragung. Die Änderungsrate unterliegt Schwankungen der Änderungsrate der Datenbank, sollte jedoch insgesamt ein Update-Intervall von 15 Minuten und somit ein RPO von 15 Minuten erreichbar sein. Wenn es 100 solche Datenbanken gibt, dann sind 600 Minuten erforderlich, um die Daten zu übertragen. Daher ist ein RPO von einer Stunde nicht möglich. Ebenso kann ein Replikat einer einzelnen Datenbank mit einer Größe von 100 TB mit einer wöchentlichen Änderungsrate von 10 % nicht innerhalb einer Stunde zuverlässig aktualisiert werden.

Zusätzliche Faktoren wie Replikations-Overhead und Beschränkungen der Anzahl gleichzeitiger Replikationsvorgänge können die Replikation beeinflussen. Die Gesamtplanung einer Replikationsstrategie für eine einzelne Ressource kann jedoch auf der verfügbaren Bandbreite basieren, und ein Replikations-RPO von einer Stunde ist in der Regel erreichbar. Ein RPO unter einer Stunde ist schwieriger zu realisieren und sollte nur nach Rücksprache mit NetApp Professional Services angestrebt werden. In einigen Fällen sind 15 Minuten bei sehr guter Standort-zu-Standort-Netzwerkverbindung möglich. Insgesamt liefert die Architektur für die Protokollwiedergabe mehrerer Ressourcen jedoch bessere Ergebnisse, wenn ein RPO unter einer Stunde erforderlich ist.

Das RTO mit Konsistenzgruppenreplikation in einem Disaster Recovery-Szenario ist ausgezeichnet, das aus Storage-Sicht in Sekunden gemessen wird. Der übersichtlichste Ansatz besteht darin, die Spiegelung zu zerbrechen und die Datenbank zu starten. Der Start der Datenbank dauert in der Regel ca. 10 Sekunden, aber sehr große Datenbanken mit vielen protokollierten Transaktionen können einige Minuten dauern.

Der wichtigere Faktor bei der Bestimmung der RTO ist nicht das Speichersystem, sondern die Anwendung und das Host-Betriebssystem, auf dem es ausgeführt wird. Die replizierten Daten können beispielsweise in ein oder zwei Sekunden verfügbar gemacht werden, aber dies stellt nur die Daten dar. Es muss auch ein korrekt konfiguriertes Betriebssystem mit Anwendungsbinärdateien vorhanden sein, um die Daten verwenden zu können.

In einigen Fällen haben Kunden Disaster-Recovery-Instanzen schon vor der Zeit vorbereitet, da der Speicher auf Betriebssystemen vorerkannt wurde. In diesen Fällen erfordert die Aktivierung des Disaster-Recovery-Szenarios nicht mehr als das Brechen einer Spiegelung und das Starten der Anwendung. In anderen Fällen können das Betriebssystem und die zugehörigen Applikationen neben der Datenbank als ESX Virtual Machine Disk (VMDK) gespiegelt werden. In diesen Fällen hängt der RPO davon ab, wie viel ein Kunde in die Automatisierung investiert hat, um die VMDK schnell zu booten und damit die Applikationen zu starten.

Die Aufbewahrungsdauer wird unter anderem durch das Snapshot-Limit bestimmt. Beispielsweise haben AFF-Volumes und ASA-LUNs in ONTAP ein Limit von 1024 Snapshots. In manchen Fällen haben Kunden die Replikation multiplexiert, um dieses Limit zu erhöhen. Wenn beispielsweise Backups für 2000 Tage benötigt werden, kann eine Quelle auf zwei verschiedene Ziele repliziert werden, wobei die Aktualisierungen an abwechselnden Tagen erfolgen. Dies erfordert eine Erhöhung des anfänglich benötigten Speicherplatzes, stellt jedoch immer noch einen wesentlich effizienteren Ansatz dar als ein herkömmliches Backup-System, das mehrere vollständige Backups umfasst.



[[single-volume-consistency-group-aff]]
=== Konsistenzgruppe für ein einzelnes Volume (AFF)

Die einfachste Methode besteht darin, alle Dateien oder LUNs in einem einzigen Volume zu speichern. Ein Volume ist eine Konsistenzgruppe für sich, was bedeutet, dass SnapMirror und SnapVault Aktualisierungen direkt auf dem Speichersystem geplant werden können. Externe Software ist nicht erforderlich.



[[single-lunnamespace-consistency-group-asa]]
=== Konsistenzgruppe für einzelne LUNs/Namespaces (ASA)

Auch wenn es ungewöhnlich erscheinen mag, eine komplette Datenbank auf einem einzigen LUN/Namespace zu platzieren, wird dies immer üblicher. Der Grund, warum Volume-Manager ursprünglich entwickelt wurden, war, die Leistungs- und Kapazitätsgrenzen physischer Laufwerke zu überwinden. Bei modernen Arrays wird ein einzelnes Blockgerät, das einem Host präsentiert wird, bereits über mehrere Laufwerke abstrahiert. Die Größe kann dynamisch angepasst werden, und die Leistung ist deutlich höher als bei einem einzelnen Laufwerk.

Das Ergebnis ist, dass Workloads von einem ESX-Datenspeicher bis hin zu einer Oracle Datenbank oft auf nur einem einzigen Blockgerät gehostet werden können. Dies vereinfacht nicht nur die Datenverwaltung erheblich, sondern hat auch hilfreiche Nebeneffekte wie schnellere Neustartzeiten des Hosts, da weniger Geräte erkannt werden müssen.



[[multi-volume-consistency-group]]
=== Konsistenzgruppe mit mehreren Volumes

Wenn eine Datenbank sich über AFF-Volumes oder ASA-LUNs/Namespaces erstrecken muss, ist ein Konsistenzgruppen-Snapshot erforderlich. Wie oben erwähnt, kann dies mit dem System Manager oder RESTful-API-Aufrufen konfiguriert werden, außerdem ist SnapCenter in der Lage, einen einfachen Konsistenzgruppen-Snapshot zu erstellen.

Es gibt auch eine zusätzliche Überlegung bei der Verwendung von AFF Multi-Volume- oder ASA Multi-LUN-Konsistenz-Snapshots für Zwecke der Notfallwiederherstellung. Wenn mehrere SnapMirror-Beziehungen aktualisiert werden, kann es passieren, dass während einer noch laufenden Übertragung ein Desaster eintritt. Das Ergebnis wäre eine Gruppe von Volumes, LUNs oder Namespaces, die nicht miteinander konsistent sind. Wenn dies geschieht, müssen einige der Volumes auf einen früheren Snapshot-Zustand zurückgesetzt werden, um ein Datenbankabbild bereitzustellen, das absturzkonsistent und einsatzbereit ist.



[[disaster-recovery-activation]]
== Disaster Recovery: Aktivierung



[[nfs]]
=== NFS

Der Prozess zur Aktivierung der Disaster Recovery-Kopie hängt vom Speichertyp ab. Mit NFS können die Dateisysteme auf dem Disaster Recovery-Server vorgemountet werden. Sie befinden sich im schreibgeschützten Zustand und werden Lese- und Schreibzugriff, wenn die Spiegelung beschädigt ist. Dadurch verkürzen sich die RPO-Werte, und der gesamte Disaster Recovery-Prozess ist zuverlässiger, da weniger Teile gemanagt werden müssen.



[[san]]
=== San

Die Aktivierung von SAN-Konfigurationen im Falle einer Disaster Recovery wird komplizierter. Die einfachste Option besteht im Allgemeinen darin, die Spiegelungen vorübergehend zu unterbrechen und die SAN-Ressourcen zu mounten, einschließlich Schritte wie das Erkennen der LVM-Konfiguration (einschließlich anwendungsspezifischer Funktionen wie Oracle Automatic Storage Management [ASM]) und das Hinzufügen von Einträgen zu /etc/fstab.

Dies führt dazu, dass die LUN-Gerätepfade, Namen von Volume-Gruppen und andere Gerätepfade dem Zielserver bekannt werden. Diese Ressourcen können dann heruntergefahren und anschließend die Spiegelungen wiederhergestellt werden. Als Folge dessen befindet sich ein Server, durch den die Applikation schnell online geschaltet werden kann. Die einzelnen Schritte zur Aktivierung von Volume-Gruppen, zum Mounten von Dateisystemen oder zum Starten von Datenbanken und Anwendungen lassen sich einfach automatisieren.

Es ist unbedingt zu beachten, dass die Disaster-Recovery-Umgebung auf dem neuesten Stand ist. Beispielsweise werden neue LUNs wahrscheinlich dem Quellserver hinzugefügt. Das bedeutet, dass die neuen LUNs auf dem Ziel vorab erkannt werden müssen, damit der Disaster-Recovery-Plan wie erwartet funktioniert.
