= AFF SSD-Aggregate und ASA Storage Availability Zones
:allow-uri-read: 


Freier Speicherplatz ist definiert als jeglicher Speicherplatz, der nicht für tatsächliche Daten verwendet wird und umfasst nicht zugewiesenen Speicherplatz auf dem Aggregat selbst sowie ungenutzten Speicherplatz innerhalb der einzelnen Volumes. Thin Provisioning muss ebenfalls berücksichtigt werden. Beispielsweise kann ein AFF-Volume eine 1-TB-LUN enthalten, von der nur 50 % durch tatsächliche Daten belegt sind. In einer Thin-Provisioning-Umgebung würde dies korrekterweise 500 GB Speicherplatz belegen. In einer vollständig bereitgestellten Umgebung hingegen scheint die volle Kapazität von 1 TB genutzt zu werden. Die 500 GB nicht zugewiesener Speicherplatz bleiben verborgen. Dieser Speicherplatz wird von tatsächlichen Daten nicht genutzt und sollte daher in die Berechnung des gesamten freien Speicherplatzes einbezogen werden.

NetApp Empfehlungen für Storage-Systeme, die für Enterprise-Applikationen verwendet werden, sind wie folgt:



[[aff-ssd-aggregates-and-asa-storage-availability-zones]]
== AFF SSD-Aggregate und ASA Storage Availability Zones


TIP: *NetApp empfiehlt* mindestens 10% freien Platz. Dazu gehört der gesamte ungenutzte Speicherplatz, einschließlich freiem Speicherplatz innerhalb des Aggregats oder eines Volumes und sämtlicher freier Speicherplatz, der aufgrund der vollständigen Bereitstellung zugewiesen wird, aber nicht von tatsächlichen Daten genutzt wird. Logischer Speicherplatz ist dabei unwichtig. Die Frage lautet, wie viel tatsächlich freier physischer Speicherplatz für Daten zur Verfügung steht.

Die Empfehlung von 10 % freiem Platz ist sehr konservativ. SSD-Aggregate können Workloads mit noch höherer Auslastung ohne Auswirkungen auf die Performance unterstützen. Wenn die Auslastung des Aggregats jedoch nicht sorgfältig überwacht wird, steigt auch das Risiko, dass der Speicherplatz nicht ausgelastet wird. Darüber hinaus kann es bei der Ausführung eines Systems mit einer Kapazität von 99 % nicht zu einer Performance-Beeinträchtigung kommen, doch wäre damit wahrscheinlich ein Management-Aufwand verbunden, um zu verhindern, dass das System während der Bestellung zusätzlicher Hardware vollständig gefüllt wird. Zudem kann es einige Zeit dauern, bis zusätzliche Laufwerke beschaffen und installiert sind.



[[hdd-aggregates-including-flash-pool-aggregates]]
== HDD-Aggregate, einschließlich Flash Pool Aggregaten


TIP: *NetApp empfiehlt* mindestens 15% freien Speicherplatz, wenn rotierende Laufwerke verwendet werden. Dazu gehört der gesamte ungenutzte Speicherplatz, einschließlich freiem Speicherplatz innerhalb des Aggregats oder eines Volumes und sämtlicher freier Speicherplatz, der aufgrund der vollständigen Bereitstellung zugewiesen wird, aber nicht von tatsächlichen Daten genutzt wird. Die Performance wird beeinträchtigt, da der freie Speicherplatz sich etwa bei 10 % befindet.
