= Fibre Channel
:allow-uri-read: 




[[fiber-channel]]
=== Fibre Channel

Ab ONTAP 9.19.1 wird Direct-Connect FC sowohl mit herkömmlichem FC-SAN (SCSI) als auch mit NVMe/FC mit ausgewählten FC-Adaptern für Speichersysteme unterstützt. Die HBAs stellen eine standardmäßige Punkt-zu-Punkt-FC-Verbindung her. Vor ONTAP 9.19.1 erfordern ONTAP Speichersysteme NPIV, was bedeutet, dass das Speichersystem mit einem FC Switch verbunden sein muss, der ebenfalls NPIV unterstützt.



[[iscsi-and-nvmetcp]]
=== ISCSI und NVMe/TCP

Ein Host, der iSCSI oder NVMe/TCP verwendet, kann direkt mit einem Storage-System verbunden werden und ordnungsgemäß ausgeführt werden. Der Grund dafür ist Pathing. Direkte Verbindungen zu zwei verschiedenen Storage Controllern ergeben zwei unabhängige Pfade für den Datenfluss. Der Verlust von Pfad, Port oder Controller verhindert nicht, dass der andere Pfad verwendet wird.



[[nfs]]
=== NFS

Direct-Connected NFS Storage kann genutzt werden, aber mit einer erheblichen Einschränkung - Failover funktioniert nicht ohne einen erheblichen Scripting-Aufwand, der in der Verantwortung des Kunden liegt.

Der Grund, warum ein unterbrechungsfreier Failover mit direkt verbundenem NFS-Storage kompliziert ist, ist das Routing auf dem lokalen Betriebssystem. Angenommen, ein Host hat eine IP-Adresse von 192.168.1.1/24 und ist direkt mit einem ONTAP-Controller mit einer IP-Adresse von 192.168.1.50/24 verbunden. Während eines Failovers kann diese 192.168.1.50-Adresse ein Failover auf den anderen Controller durchführen, und sie wird für den Host verfügbar sein. Wie erkennt der Host jedoch sein Vorhandensein? Die ursprüngliche 192.168.1.1-Adresse ist noch auf der Host-NIC vorhanden, die keine Verbindung mehr zu einem Betriebssystem herstellt. Der für 192.168.1.50 bestimmte Datenverkehr würde weiterhin an einen nicht funktionsfähigen Netzwerkport gesendet.

Die zweite OS-NIC könnte als 192.168.1.2 konfiguriert werden und wäre in der Lage, mit der übergewechselten Adresse 192.168.1.50 zu kommunizieren, aber die lokalen Routingtabellen hätten standardmäßig die Vorgabe, eine *und nur eine* Adresse für die Kommunikation mit dem Subnetz 192.168.1.0/24 zu verwenden. Ein Systemadministrator könnte ein Skripting-Framework erstellen, das einen Ausfall der Netzwerkverbindung erkennt und die lokalen Routingtabellen anpasst oder Schnittstellen aktiviert und deaktiviert. Das genaue Verfahren würde vom verwendeten Betriebssystem abhängen.

In der Praxis haben NetApp-Kunden NFS direkt verbunden, aber normalerweise nur für Workloads, bei denen IO-Pausen während Failover akzeptabel sind. Wenn harte Mounts verwendet werden, sollte es während solcher Pausen keine IO-Fehler geben. Die E/A-Vorgänge sollten so lange hängen bleiben, bis Dienste wiederhergestellt werden, entweder durch ein Failback oder durch einen manuellen Eingriff, um IP-Adressen zwischen NICs auf dem Host zu verschieben.
