= Best Practices für Effizienz
:allow-uri-read: 




== Best Practices für Effizienz

*NetApp empfiehlt* Folgendes:



=== AFF und ASA Standardeinstellungen

Volumes, die auf ONTAP auf AFF Systemen erstellt wurden, sowie LUNs/Namespaces auf ASA Systemen sind Thin Provisioned mit allen aktivierten Inline-Effizienzfunktionen. Obwohl Datenbanken im Allgemeinen nicht von Deduplizierung profitieren und nicht komprimierbare Daten enthalten können, sind die Standardeinstellungen dennoch für nahezu alle Workloads geeignet. ONTAP ist darauf ausgelegt, alle Datentypen und I/O-Muster effizient zu verarbeiten, unabhängig davon, ob sie Einsparungen bewirken. Standardeinstellungen sollten nur geändert werden, wenn die Gründe vollständig verstanden werden und eine Abweichung einen Vorteil bringt.



=== Allgemeine Empfehlungen

* Wenn AFF-Volumes, LUNs oder Namespaces nicht Thin Provisioning verwenden, müssen Sie alle Effizienzeinstellungen deaktivieren, da die Verwendung dieser Funktionen keine Einsparungen bringt und die Kombination von Thick Provisioning mit aktivierter Speicherplatzeffizienz zu unerwartetem Verhalten, einschließlich Speicherplatzfehlern, führen kann.
* Wenn Daten nicht überschrieben werden, wie etwa bei Backups oder Datenbanktransaktionsprotokollen, können Sie die Effizienz steigern, indem Sie TSSE mit einem niedrigen Kühlzeitraum aktivieren.
* Einige Dateien enthalten möglicherweise eine beträchtliche Menge an nicht komprimierbaren Daten. Ein Beispiel: Wenn die Komprimierung bereits auf Applikationsebene aktiviert ist, werden Dateien verschlüsselt. Wenn eines dieser Szenarien zutrifft, sollten Sie die Komprimierung deaktivieren, um einen effizienteren Betrieb auf anderen Volumes mit komprimierbaren Daten zu ermöglichen.
* Verwenden Sie für Datenbank-Backups nicht sowohl die 32-KB-Komprimierung als auch die Deduplizierung. Siehe Abschnitt <<Anpassungsfähige Komprimierung>> Entsprechende Details.

