---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: Disaster Recovery für Microsoft SQL Server mit ONTAP 
---
= Disaster Recovery für Microsoft SQL Server mit ONTAP
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Enterprise-Datenbanken und Applikationsinfrastrukturen erfordern oft Replizierung zum Schutz vor Naturkatastrophen oder unerwarteten Geschäftsunterbrechungen mit minimaler Ausfallzeit.

Die SQL Server Funktion zur Always-on-Replikation von Verfügbarkeitsgruppen kann eine hervorragende Option sein. NetApp bietet Optionen zur Integration der Datensicherheit mit Always-on. In einigen Fällen empfiehlt es sich jedoch, die ONTAP Replizierungstechnologie in Betracht zu ziehen. ONTAP Replizierungsoptionen wie MetroCluster und SnapMirror lassen sich mit minimalen Auswirkungen auf die Performance besser skalieren. Zudem werden nicht SQL-fremde Daten geschützt und im Allgemeinen ist eine Replizierungs- und DR-Lösung für die gesamte Infrastruktur vorhanden.



== SnapMirror asynchron

Die SnapMirror Technologie bietet eine schnelle und flexible asynchrone Unternehmenslösung zur Replizierung von Daten über LANs und WANs. Dank der SnapMirror Technologie werden nach Erstellung der ersten Spiegelung nur geänderte Datenblöcke an das Zielsystem übertragen, wodurch die Anforderungen an die Netzwerkbandbreite erheblich verringert werden.

Nachfolgend finden Sie Empfehlungen für SnapMirror für SQL Server:

* Bei Verwendung von CIFS muss die Ziel-SVM Mitglied derselben Active Directory-Domäne sein, der die Quell-SVM angehört, damit die in NAS-Dateien gespeicherten Zugriffssteuerungslisten (Access Control Lists, ACLs) während der Wiederherstellung nach einem Notfall nicht beschädigt werden.
* Die Verwendung von Ziel-Volume-Namen, die mit den Namen des Quell-Volume übereinstimmen, ist nicht erforderlich, kann jedoch das Mounten von Ziel-Volumes in das Ziel einfacher gestalten. Wenn CIFS verwendet wird, müssen Sie den Ziel-NAS-Namespace in Pfaden und Verzeichnisstruktur mit dem Quell-Namespace identisch machen.
* Aus Konsistenzgründen sollten Sie keine SnapMirror Updates von den Controllern planen. Stattdessen sollten Sie SnapMirror Updates von SnapCenter aktivieren, um SnapMirror zu aktualisieren, nachdem ein vollständiger Backup oder ein Protokoll-Backup abgeschlossen wurde.
* Verteilen Sie Volumes, die SQL Server-Daten enthalten, auf verschiedene Nodes im Cluster, damit alle Clusterknoten SnapMirror-Replikationsaktivitäten gemeinsam nutzen können. Diese Verteilung optimiert die Nutzung von Knotenressourcen.


Weitere Informationen zu SnapMirror finden Sie unter link:https://www.netapp.com/us/media/tr-4015.pdf["TR-4015: SnapMirror Konfigurations- und Best Practices-Leitfaden für ONTAP 9"^].
