---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: Disaster Recovery für Microsoft SQL Server mit ONTAP 
---
= Disaster Recovery für Microsoft SQL Server mit ONTAP
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Enterprise-Datenbanken und Applikationsinfrastrukturen erfordern oft Replizierung zum Schutz vor Naturkatastrophen oder unerwarteten Geschäftsunterbrechungen mit minimaler Ausfallzeit.

Die SQL Server Funktion zur Replizierung von Always-on-Verfügbarkeitsgruppen kann sich als hervorragende Option anbieten. NetApp bietet Optionen zur Integration von Datensicherung mit Always-on. In einigen Fällen empfiehlt es sich jedoch, die ONTAP Replizierungstechnologie in Betracht zu ziehen. Es gibt drei grundlegende Optionen.



== SnapMirror

Die SnapMirror-Technologie bietet eine schnelle und flexible Unternehmenslösung zur Replizierung von Daten über LANs und WANs. Die SnapMirror Technologie überträgt nach Erstellung der ersten Spiegelung nur geänderte Datenblöcke an das Zielsystem, wodurch die Anforderungen an die Netzwerkbandbreite erheblich gesenkt werden. Sie kann im synchronen oder asynchronen Modus konfiguriert werden.



== NetApp MetroCluster

MetroCluster Konfigurationen unterstützen die Bereitstellung von Hochverfügbarkeits-Storage-Lösungen ohne Datenverluste für Applikationen, Datenbanken und Virtualisierungsplattformen. Die Lösung wird mit einer Kombination aus Array-basiertem Clustering und synchroner Replizierung implementiert, die eine zusätzliche Sicherungsebene für die gesamte Storage- und Host-Umgebung bietet.



== SnapMirror Active Sync (ehemals SnapMirror Business Continuity)

SnapMirror Active Sync basiert auf SnapMirror Synchronous und seiner Fähigkeit, mehrere LUNs auf repliziertem Storage zu replizieren, wobei die Konsistenz der Schreibreihenfolge beibehalten wird. Bei MetroCluster sollte der ONTAP Controller einschließlich Netzwerkkonfiguration standortübergreifend identisch sein. Bei SnapMirror Active Sync haben Sie im Grunde zwei verschiedene ONTAP-Systeme, die unabhängige Kopien Ihrer LUN-Daten führen, aber zusammenarbeiten, um eine einzige Instanz dieser LUN zu präsentieren. Auf Host-Ebene handelt es sich um eine einzelne LUN-Einheit.

Der Hauptunterschied zwischen MetroCluster und SnapMirror Active Sync ist Granularität und Skalierbarkeit. Wenn Sie bestimmte Workloads für die synchrone Replizierung auswählen müssen oder LUNs für Lese-/Schreibvorgänge an beiden Standorten verfügbar sein sollten, ist SnapMirror Active Sync die bessere Option. Wenn ganze Umgebungen oder sogar Datacenter repliziert werden müssen, ist MetroCluster die bessere Option. Darüber hinaus ist SnapMirror Active Sync derzeit nur für SAN verfügbar und MetroCluster unterstützt mehrere Protokolle, einschließlich SAN, NFS und SMB.

Weitere Informationen über SnapMirror finden Sie unter link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015pdf.pdf["TR-4015: SnapMirror Konfigurations- und Best Practices-Leitfaden für ONTAP 9"^].
