---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MSSQL,SQL Server,TR-4590, SnapCenter, ONTAP 
summary: Microsoft SQL Server auf ONTAP 
---
= Microsoft SQL Server auf ONTAP
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
ONTAP bietet eine Sicherheits- und Performance-Lösung der Enterprise-Klasse für Ihre Microsoft SQL Server Datenbanken und stellt gleichzeitig erstklassige Tools für das Management Ihrer Umgebung bereit.


NOTE: Diese Dokumentation ersetzt den zuvor veröffentlichten technischen Bericht _TR-4590: Best Practice Guide for Microsoft SQL Server with ONTAP_

NetApp geht davon aus, dass der Leser über die folgenden Kenntnisse verfügt:

* ONTAP Software
* NetApp SnapCenter als Backup-Software, einschließlich:
+
** SnapCenter Plug-in für Microsoft Windows
** SnapCenter Plug-in für SQL Server


* Architektur und Administration von Microsoft SQL Server


Dieser Abschnitt zu Best Practices beschränkt sich auf technisches Design basierend auf den Design-Prinzipien und bevorzugten Standards, die NetApp für die Storage-Infrastruktur empfiehlt. Die End-to-End-Implementierung ist nicht im Umfang enthalten.

Informationen zur Kompatibilität der Konfigurationen mit den NetApp Produkten finden Sie im link:https://mysupport.netapp.com/matrix/["NetApp Interoperabilitäts-Matrix-Tool (IMT)"^].



== Microsoft SQL Server-Workloads

Vor der Bereitstellung von SQL Server müssen Sie die Anforderungen an die Datenbank-Workloads der Anwendungen kennen, die von Ihren SQL Server-Instanzen unterstützt werden. Jede Applikation hat unterschiedliche Anforderungen an Kapazität, Performance und Verfügbarkeit. Daher sollte jede Datenbank für eine optimale Unterstützung dieser Anforderungen entworfen werden. Viele Unternehmen klassifizieren Datenbanken in mehrere Management-Tiers unter Verwendung von Anwendungsanforderungen zur Definition von SLAs. SQL Server-Workloads können wie folgt beschrieben werden:

* OLTP-Datenbanken sind oft auch die kritischsten Datenbanken eines Unternehmens. Diese Datenbanken stehen in der Regel kundenorientierten Applikationen gegenüber und werden als unverzichtbar für die Kernprozesse des Unternehmens angesehen. Für geschäftskritische OLTP-Datenbanken und die von ihnen unterstützten Applikationen gibt es oft SLAs, die ein hohes Maß an Performance erfordern und mit hohen Anforderungen an Performance-Verschlechterung und Verfügbarkeit verbunden sind. Sie können auch Kandidaten für „Always On“-Failover-Cluster oder „Always On“-Verfügbarkeitsgruppen sein. Der I/O-Mix dieser Datenbanktypen ist in der Regel durch 75 bis 90 % zufällige Lesevorgänge und 25 bis 10 % Schreibzugriffe gekennzeichnet.
* Datenbanken des Decision Support System (DSS) können auch als Data Warehouses bezeichnet werden. Diese Datenbanken sind in vielen Unternehmen, die auf Analysen für ihr Geschäft vertrauen, geschäftskritisch. Diese Datenbanken sind sensibel für die CPU-Auslastung und Lesevorgänge von der Festplatte, wenn Abfragen ausgeführt werden. In vielen Unternehmen sind DSS-Datenbanken zum Monats-, Quartals- und Jahresende am wichtigsten Dieser Workload verfügt in der Regel über eine I/O-Kombination mit 100 % Lesevorgängen.

