---
sidebar: sidebar 
permalink: mssql/mssql-storage-considerations.html 
keywords: MS-SQL,mssql,SQL Server 
summary: Microsoft SQL Server auf ONTAP 
---
= Überlegungen zum Microsoft SQL Server-Storage
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Die Kombination aus NetApp Storage-Lösungen und Microsoft SQL Server ermöglicht die Erstellung von Datenbank-Storage-Designs der Enterprise-Klasse, die den anspruchsvollsten Applikationsanforderungen von heute gerecht werden.

Um beide Technologien zu optimieren, ist es wichtig, das SQL Server-I/O-Muster und die Merkmale zu verstehen. Ein gut geplantes Storage-Layout für eine SQL Server Datenbank unterstützt die Performance von SQL Server und das Management der SQL Server Infrastruktur. Ein gutes Storage-Layout ermöglicht außerdem eine erfolgreiche Erstimplementierung und ein reibungsloses Wachstum der Umgebung im Laufe der Zeit, während das Unternehmen wächst.



== Datenspeicher Design

Für SQL Server-Datenbanken, die keine Backups mit SnapCenter durchführen, empfiehlt Microsoft, die Daten und Log-Dateien auf separaten Laufwerken zu platzieren. Bei Anwendungen, die gleichzeitig Daten aktualisieren und anfordern, ist die Protokolldatei schreibintensiv und die Datendatei (je nach Anwendung) ist Lese-/schreibintensiv. Für den Datenabruf wird die Protokolldatei nicht benötigt. Daher können Datenanfragen aus der Datendatei auf dem eigenen Laufwerk bearbeitet werden.

Wenn Sie eine neue Datenbank erstellen, empfiehlt Microsoft, getrennte Laufwerke für die Daten und Protokolle anzugeben. Um Dateien nach der Datenbankerstellung zu verschieben, muss die Datenbank offline geschaltet werden. Weitere Empfehlungen von Microsoft finden Sie unter link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["Platzieren Sie Daten- und Protokolldateien auf separaten Laufwerken"^].



== Aggregate

Aggregate sind die primären Storage-Container für NetApp Storage-Konfigurationen und enthalten eine oder mehrere RAID-Gruppen, die sowohl Daten- als auch Parity-Festplatten bestehen. NetApp hat verschiedene I/O-Workload-Merkmalstests mit gemeinsam genutzten und dedizierten Aggregaten mit getrennten Datendateien und Transaktions-Log-Dateien durchgeführt. Die Tests zeigen, dass ein großes Aggregat mit mehr RAID-Gruppen und Spindeln die Storage Performance optimiert und verbessert und Administratoren aus zwei Gründen einfacher zu managen sind:

* Ein großes Aggregat macht die I/O-Fähigkeiten aller Spindeln für alle Dateien verfügbar.
* Ein großes Aggregat ermöglicht die effizienteste Nutzung von Festplattenspeicher.


Platzieren Sie für Hochverfügbarkeit (HA) das sekundäre synchrone Replikat der SQL Server Always On Availability Group auf einer separaten Storage Virtual Machine (SVM) im Aggregat. Platzieren Sie zum Zweck der Disaster Recovery das asynchrone Replikat in einem Aggregat, das Teil eines separaten Storage-Clusters am DR-Standort ist, und Inhalte werden mithilfe der NetApp SnapMirror Technologie repliziert. NetApp empfiehlt eine Verfügbarkeit von mindestens 10 % freien Speicherplatz in einem Aggregat zugunsten der optimalen Storage-Performance.



== Volumes

NetApp FlexVol Volumes werden erstellt und befinden sich in den Aggregaten. Zahlreiche Volumes können in einem einzigen Aggregat erstellt werden. Jedes Volume kann ohne Ausfallzeit für die Benutzer erweitert, verkleinert oder zwischen Aggregaten verschoben werden.



=== Überlegungen zum Volume-Design

Bevor Sie ein Datenbank-Volume-Design erstellen, ist es wichtig zu wissen, wie das I/O-Muster und die Merkmale von SQL Server je nach Workload und Backup- und Recovery-Anforderungen variieren. Beachten Sie die folgenden NetApp Empfehlungen für flexible Volumes:

* Verwenden Sie flexible Volumes, um SQL Server-Datenbankdateien zu speichern und die gemeinsame Nutzung von Volumes zwischen Hosts zu vermeiden.
* Verwenden Sie NTFS-Bereitstellungspunkte anstelle von Laufwerksbuchstaben, um die Beschränkung auf 26 Laufwerksbuchstaben in Windows zu überschreiten. Bei der Verwendung von Volume-Mount-Punkten wird generell empfohlen, dem Volume-Label den gleichen Namen wie dem Mount-Punkt zu geben.
* Konfigurieren Sie bei Bedarf eine Richtlinie für die automatische Größenanpassung von Volumes, um Speicherplatzbelegung zu verhindern. 17 Best Practice Guide für Microsoft SQL Server mit ONTAP © 2022 NetApp, Inc Alle Rechte vorbehalten.
* Aktivieren Sie die Optimierung für Lesezugriffe auf dem Volume, wenn das I/O-Profil der SQL Server-Datenbank aus überwiegend großen sequenziellen Lesezugriffen besteht, beispielsweise mit System-Workloads zur Entscheidungsunterstützung. Die Optimierung der Lesezugriffe optimiert die Blöcke, um eine bessere Performance zu erzielen.
* Wenn Sie SQL Server auf einer SMB-Freigabe installieren, stellen Sie sicher, dass Unicode auf den SMB/CIFS-Volumes zum Erstellen von Ordnern aktiviert ist.
* Setzen Sie den Wert der Reserve von NetApp Snapshot Kopien im Volume auf null, um die Überwachung aus betrieblicher Sicht zu vereinfachen.
* Deaktivieren Sie Zeitpläne und Aufbewahrungsrichtlinien für Storage Snapshot™ Kopien. Stattdessen können Sie SnapCenter verwenden, um Snapshot Kopien der SQL Server-Daten-Volumes zu koordinieren.
* Platzieren Sie die SQL Server Systemdatenbanken auf einem dedizierten Volume oder einer VMDK.
* Tempdb ist eine Systemdatenbank, die von SQL Server als temporärer Arbeitsbereich verwendet wird, insbesondere für I/O-intensive DBCC-CHECKDB-Vorgänge. Platzieren Sie diese Datenbank daher auf einem dedizierten Volume mit einem separaten Satz von Spindeln. In großen Umgebungen, in denen die Volume-Anzahl eine Herausforderung ist, können Sie tempdb in weniger Volumes konsolidieren und im gleichen Volume wie andere Systemdatenbanken nach einer sorgfältigen Planung speichern. Datenschutz für tempdb hat keine hohe Priorität, da diese Datenbank bei jedem Neustart von SQL Server neu erstellt wird.
* Platzieren Sie Benutzerdatendateien (.mdf) auf separaten Volumes, da es sich um Workloads mit zufälligen Lese-/Schreibzugriffen handelt. Es ist üblich, Transaktions-Log-Backups häufiger zu erstellen als Datenbank-Backups. Legen Sie aus diesem Grund Transaktions-Log-Dateien (.ldf) auf ein separates Volume oder VMDK aus den Datendateien, so dass für jede Datei unabhängige Backup-Zeitpläne erstellt werden können. Durch diese Trennung werden auch die I/O-Vorgänge bei sequenziellen Schreibvorgängen aus den I/O-Vorgängen für zufällige Lese-/Schreibzugriffe von Datendateien isoliert und die SQL Server Performance deutlich verbessert.




== LUN

* Stellen Sie sicher, dass sich die Benutzerdatenbankdateien und das Protokollverzeichnis für das Protokoll-Backup auf separaten Volumes befinden, damit die Aufbewahrungsrichtlinie Snapshots bei Verwendung der SnapVault-Technologie nicht überschreibt.
* Stellen Sie sicher, dass sich SQL Server-Datenbanken auf LUNs befinden, die von LUNs getrennt sind, die keine Datenbankdateien enthalten, z. B. Dateien für die Volltextsuche.
* Wenn sekundäre Datenbankdateien (als Teil einer Dateigruppe) auf separate Volumes platziert werden, wird die Performance der SQL Server Datenbank verbessert. Diese Trennung ist nur gültig, wenn die mdf-Datei der Datenbank ihre LUN nicht mit anderen mdf-Dateien teilt.
* Wenn Sie LUNs mit DiskManager oder anderen Werkzeugen erstellen, stellen Sie sicher, dass die Größe der Zuordnungseinheit beim Formatieren der LUNs auf 64K für Partitionen festgelegt ist.
* Siehe link:https://www.netapp.com/media/10680-tr4080.pdf["Microsoft Windows und natives MPIO unter den Best Practices von ONTAP für modernes SAN"] So wenden Sie Multipathing-Unterstützung unter Windows auf iSCSI-Geräte in den MPIO-Eigenschaften an.




=== Protokollverzeichnis

Das Protokollverzeichnis wird in SQL Server angegeben, um die Backup-Daten des Transaktionsprotokolls auf Hostebene zu speichern. Wenn Sie SnapCenter zum Sichern von Protokolldateien verwenden, muss für jeden von SnapCenter verwendeten SQL Server-Host ein Hostprotokollverzeichnis konfiguriert sein, um Protokollsicherungen durchzuführen. Bei SnapCenter gibt es ein Datenbank-Repository, sodass Metadaten, die mit Backup-, Restore- oder Klonvorgängen verbunden sind, in einem zentralen Datenbank-Repository gespeichert werden.

Die Größe des Host-Log-Verzeichnisses wird wie folgt berechnet:
Größe des Host-Log-Verzeichnisses = ( (maximale DB-LDF-Größe x tägliche Log-Änderungsrate %) x (Snapshot-Aufbewahrung) ÷ (1 - LUN Overhead-Speicherplatz %)
Die Formel zur Größenbestimmung des Host-Protokollverzeichnisses nimmt einen LUN Overhead von 10 % an

Platzieren Sie das Protokollverzeichnis auf einem dedizierten Volume oder LUN. Die Datenmenge im Host-Log-Verzeichnis hängt von der Größe der Backups und der Anzahl der Tage ab, die Backups aufbewahrt werden. SnapCenter erlaubt nur ein Host-Protokollverzeichnis pro SQL Server-Host. Sie können die Host-Protokollverzeichnisse unter SnapCenter --> Host --> Configure Plug-in konfigurieren.

[TIP]
====
*NetApp empfiehlt* für ein Host-Log-Verzeichnis:

* Stellen Sie sicher, dass das Host-Protokollverzeichnis nicht von anderen Datentypen gemeinsam genutzt wird, die möglicherweise die Backup-Snapshot-Daten beschädigen können.
* Platzieren Sie keine Benutzerdatenbanken oder Systemdatenbanken auf einer LUN, die Bereitstellungspunkte hostet.
* Erstellen Sie das Host-Log-Verzeichnis auf dem dedizierten FlexVol Volume, auf das SnapCenter Transaktionsprotokolle kopiert.
* Migrieren Sie Datenbanken mithilfe von SnapCenter-Assistenten in NetApp Storage, damit die Datenbanken an gültigen Speicherorten gespeichert werden und so erfolgreiche SnapCenter-Backup- und -Restore-Vorgänge ermöglichen. Beachten Sie, dass der Migrationsprozess für den Fall von Unterbrechungen verantwortlich ist und dazu führen kann, dass die Datenbanken offline gehen, während die Migration durchgeführt wird.
* Die folgenden Bedingungen müssen für Failover-Cluster-Instanzen (FCIs) von SQL Server gelten:
+
** Wenn Sie eine Failover-Cluster-Instanz verwenden, muss das Host-Log-Verzeichnis LUN eine Cluster-Festplattenressource in derselben Cluster-Gruppe sein wie die SQL Server-Instanz, die SnapCenter gesichert wird.
** Wenn Sie eine Failover-Cluster-Instanz verwenden, müssen Benutzerdatenbanken auf gemeinsam genutzte LUNs platziert werden, bei denen es sich um physische Festplatten-Cluster-Ressourcen handelt, die der Cluster-Gruppe zugewiesen sind, die der SQL Server-Instanz zugeordnet ist.




====