---
sidebar: sidebar 
permalink: mssql/SQL-disaster-recovery.html 
keywords: MS-SQL,mssql,SQL Server, disaster recovery, snapmirror 
summary: Microsoft SQL Server auf ONTAP 
---
= Disaster Recovery für Microsoft SQL Server
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
NetApp bietet verschiedene Ansätze zur Verbesserung der Datenverfügbarkeit bei Hardware-, Software- oder Standortausfällen.



== NetApp SnapMirror

NetApp SnapMirror bietet eine schnelle und flexible Enterprise-Lösung zum Spiegeln oder Replizieren von Daten über LANs und WANs. Die SnapMirror Technologie überträgt nach dem ersten Basistransfer nur geänderte 4-KB-Datenblöcke zum Ziel, wodurch die Anforderungen an die Netzwerkbandbreite erheblich gesenkt werden. SnapMirror bietet asynchrone Replizierung auf Volume-Ebene, die auf einem konfigurierten Update-Intervall für die Replizierung basiert.
Nachfolgend finden Sie Empfehlungen für SnapMirror für SQL Server:

* Bei Verwendung von CIFS muss die Ziel-SVM Mitglied derselben Active Directory-Domäne sein, der die Quell-SVM angehört, damit die in NAS-Dateien gespeicherten Zugriffssteuerungslisten (Access Control Lists, ACLs) während der Wiederherstellung nach einem Notfall nicht beschädigt werden.
* Die Verwendung von Ziel-Volume-Namen, die mit den Namen des Quell-Volume übereinstimmen, ist nicht erforderlich, kann jedoch das Mounten von Ziel-Volumes in das Ziel einfacher gestalten. Wenn CIFS verwendet wird, müssen Sie den Ziel-NAS-Namespace in Pfaden und Verzeichnisstruktur mit dem Quell-Namespace identisch machen.
* Aus Konsistenzgründen sollten Sie die SnapMirror Aktualisierung nicht von den Controllern planen. Aktivieren Sie jedoch das SnapMirror Update von SnapCenter, um SnapMirror zu aktualisieren, nachdem ein vollständiger oder ein Protokoll-Backup abgeschlossen wurde.
* Verteilen Sie Volumes, die SQL Server-Daten enthalten, auf verschiedene Nodes im Cluster, damit alle Clusterknoten SnapMirror-Replikationsaktivitäten gemeinsam nutzen können. Diese Verteilung optimiert die Nutzung von Knotenressourcen.


Weitere Informationen zu SnapMirror finden Sie unter link:https://www.netapp.com/us/media/tr-4015.pdf["TR-4015: SnapMirror Konfigurations- und Best Practices-Leitfaden für ONTAP 9"^].
