---
sidebar: sidebar 
permalink: mssql/sql-data-protection.html 
keywords: MS-SQL,mssql,SQL Server, SnapCenter, data protection 
summary: Microsoft SQL Server Datensicherung mit ONTAP 
---
= Microsoft SQL Server Datensicherung mit ONTAP
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Die Sicherung von Datenbanken ist für jedes Unternehmen von großer Bedeutung. Da die Datenmenge und Anzahl der Datenbanken zugenommen haben, ist die Einhaltung der Recovery Time Objective (RTO) und der Recovery Point Objective (RPO) von großer Bedeutung.

Der wichtigste Faktor bei Datenbank-Backups ist die Nutzung der NetApp Snapshot Technologie. Ein applikationskonsistentes Backup und Datenbank-Layout sind weitere wichtige Kriterien für die Einhaltung von RTO und RPO, die von NetApp SnapCenter orchestriert werden können.



== SnapCenter

SnapCenter ist die NetApp Datensicherungssoftware für Enterprise-Applikationen.SQL Server Datenbanken lassen sich mit dem Plug-in für SQL Server und dem Plug-in für Microsoft Windows schnell und einfach mit NetApp SnapCenter Software sichern.

Diese Produkte ermöglichen applikationskonsistente Backups, automatisiertes Klonen sowie Restores und Recoverys von SQL Server Datenbanken, Instanzen oder Verfügbarkeitsgruppen.


TIP: *NetApp empfiehlt* SnapCenter zum Erstellen von Snapshot Kopien zu verwenden.

Weitere Informationen zum SQL Server-Plug-in für SnapCenter finden Sie unter link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: Best Practice Guide für SQL Server mit NetApp SnapCenter"^].



== Datenbanken mit T-SQL-Snapshots werden gesichert

In SQL Server 2022 hat Microsoft T-SQL Snapshots eingeführt. Diese bieten einen integrierten Vorteil als die herkömmliche Methode, die vom Datenbankadministrator nicht einfach verwendet wurde. Durch die Nutzung der ONTAP REST-APIs können Sie Befehle zu Snapshot-Volumes aufrufen.

Im Folgenden finden Sie ein Beispiel für einen Backup-Workflow:

. Eine Datenbank mit dem Befehl „ALTER“ einfrieren – damit die Möglichkeit besteht, einen konsistenten Snapshot auf dem zugrunde liegenden Speicher zu erstellen. Danach können Sie die Datenbank auftauen und den Snapshot mit dem BACKUP-Befehl aufzeichnen.
. Führen Sie Snapshots mehrerer Datenbanken auf den Speichervolumes gleichzeitig mit den neuen Befehlen BACKUP-GRUPPE und BACKUP-SERVER durch.
. Führen Sie VOLLSTÄNDIGE Backups oder COPY_ONLY VOLLSTÄNDIGE Backups durch. Diese Backups werden auch in msdb aufgezeichnet.
. Durchführung einer zeitpunktgenauen Recovery mithilfe von Protokoll-Backups, die mit dem normalen Streaming-Ansatz nach dem VOLLSTÄNDIGEN Snapshot-Backup erstellt wurden. Streaming Differential Backups werden auf Wunsch auch unterstützt.


Weitere Informationen finden Sie unter link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["Microsoft-Dokumentation zu den T-SQL-Snapshots"^].
