---
sidebar: sidebar 
permalink: mssql/storage-efficiency.html 
keywords: MS-SQL,mssql,SQL Server 
summary: Microsoft SQL Server auf ONTAP 
---
= ONTAP Storage-Effizienz mit Microsoft SQL Server
:allow-uri-read: 


[role="lead"]
Storage-Effizienz bezieht sich auf die Fähigkeit, SQL Server-Daten so zu speichern und zu managen, dass der Speicherplatz auf ein Minimum beschränkt wird und die Gesamt-Performance des Systems kaum oder gar nicht beeinträchtigt wird.

Storage-Effizienz ist eine Kombination aus RAID, Bereitstellung (Gesamtlayout und Auslastung), Spiegelung und anderen Datensicherungstechnologien. Mit NetApp Technologien wie Snapshot Kopien, Thin Provisioning und FlexClone lassen sich Kostenvorteile erzielen, indem vorhandener Storage in der Infrastruktur optimiert und künftige Storage-Ausgaben verschoben oder vermieden werden. Je öfter Sie diese Technologien kombinieren, desto größer sind die Einsparungen. Weitere Informationen finden Sie unter link:../common/ontap/thin-provisioning.html["Empfehlungen zur Bereitstellung"]

Storage-Komprimierung, Data-Compaction und Deduplizierung sind weitere Storage-Effizienzoptionen, die eine höhere logische Datenmenge für die gegebene Menge an physischem Storage erzielen. Weitere Informationen finden Sie unter link:../common/ontap/efficiency.html["Best Practices für Effizienz"].

SQL Server verfügt auch über eine Funktion zur Komprimierung und zum effizienten Management von Daten. SQL Server unterstützt derzeit zwei Arten der Datenkomprimierung: Row Compression und Page Compression.

Durch die Zeilenkomprimierung wird das Datenspeicherformat geändert. So werden beispielsweise ganze Zahlen und Dezimalzahlen anstelle des nativen Formats mit fester Länge in das Format mit variabler Länge geändert. Außerdem werden Zeichenketten mit fester Länge durch das Entfernen von Leerzeichen in das Format mit variabler Länge geändert. Die Seitenkomprimierung implementiert die Zeilenkomprimierung und zwei weitere Komprimierungsstrategien (Prefix-Komprimierung und Wörterbuchkomprimierung). Weitere Details zur Seitenkomprimierung finden Sie unter link:https://learn.microsoft.com/en-us/sql/relational-databases/data-compression/page-compression-implementation?view=sql-server-ver16&redirectedfrom=MSDN["Implementierung Der Seitenkomprimierung"^].

Die Datenkomprimierung wird derzeit in den Enterprise-, Developer- und Evaluation-Editionen von SQL Server 2008 und höher unterstützt. Obwohl die Komprimierung von der Datenbank selbst durchgeführt werden kann, ist dies in einer SQL Server Umgebung nur selten der Fall.

Hier sind die Empfehlungen für die Verwaltung von Speicherplatz für SQL Server-Datendateien

* Verwenden Sie Thin Provisioning in SQL Server-Umgebungen, um die Speicherplatzauslastung zu verbessern und bei Einsatz der Speicherplatzgarantiefunktion den gesamten Storage-Bedarf zu senken.
* Verwenden Sie Autogrow für die meisten gängigen Implementierungskonfigurationen, da der Storage-Administrator nur die Speicherplatznutzung im Aggregat überwachen muss.
* Es empfiehlt sich, die Deduplizierung auf Volumes mit SQL Server-Datendateien nicht zu aktivieren, es sei denn, das Volume enthält bekanntermaßen mehrere Kopien derselben Daten, wie beispielsweise das Wiederherstellen von Datenbanken aus Backups auf einem einzelnen Volume.




== Speicherplatzrückgewinnung

Die Rückgewinnung von ungenutztem Speicherplatz in einer LUN kann regelmäßig gestartet werden. Bei SnapCenter können Sie den folgenden PowerShell Befehl verwenden, um die Rückgewinnung von ungenutztem Speicherplatz zu starten.

[listing]
----
Invoke-SdHostVolumeSpaceReclaim -Path drive_path
----
Wenn Sie die Speicherplatzrückgewinnung durchführen müssen, sollte dieser Prozess in Zeiten geringer Aktivität ausgeführt werden, da er anfangs Hostzyklen beansprucht.
