---
sidebar: sidebar 
permalink: oracle/dr/snapmirror/snapmirror.html 
keywords: ontap, snapmirror 
summary: SnapMirror und SyncMirror 
---
= SnapMirror und SyncMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../../media/


[role="lead"]
Nahezu jede Applikation erfordert Datenreplizierung.

Auf der einfachsten Ebene kann Replikation eine Kopie auf einem externen Band oder eine Replikation auf Anwendungsebene an einem Standby-Standort bedeuten. Bei Disaster Recovery werden diese Replikatkopien verwendet, um bei einem katastrophalen Serviceausfall einen Service online zu schalten.

ONTAP bietet mehrere Replizierungsoptionen, um eine Vielzahl von Anforderungen nativ innerhalb des Storage Array zu erfüllen und so ein breites Spektrum an Anforderungen abzudecken. Diese Optionen können die einfache Replizierung von Backups an einen Remote-Standort bis hin zu einer synchronen, voll automatisierten Lösung umfassen, die sowohl Disaster Recovery als auch Hochverfügbarkeit auf derselben Plattform bietet.

Die primären ONTAP Replizierungstechnologien, die für Applikationen anwendbar sind, sind NetApp SnapMirror und NetApp SyncMirror. Es handelt sich nicht um Add-on-Produkte, sondern sie sind vollständig in ONTAP integriert und werden durch das einfache Hinzufügen eines Lizenzschlüssels aktiviert. Auch die Replizierung auf Storage-Ebene ist nicht die einzige Option. Replizierung auf Applikationsebene wie Oracle DataGuard kann ebenfalls in eine auf ONTAP basierende Datensicherungsstrategie integriert werden.

Die richtige Wahl hängt von den spezifischen Replizierungs-, Recovery- und Aufbewahrungsanforderungen ab.



== ONTAP SnapMirror

SnapMirror ist die asynchrone Replizierungslösung von NetApp und eignet sich ideal für die Sicherung großer, komplizierter und dynamischer Datensätze wie Datenbanken und zugehöriger Applikationen. Die wichtigsten Werte lauten wie folgt:

* *Manageability.* SnapMirror ist einfach zu konfigurieren und zu verwalten, da es ein nativer Teil der Speichersoftware ist. Es sind keine Add-on-Produkte erforderlich. Replizierungsbeziehungen lassen sich innerhalb von Minuten einrichten und direkt auf dem Storage-System managen.
* *Einfachheit.* die Replikation basiert auf FlexVol-Volumes, die Container von LUNs oder Dateien sind, die als einheitliche konsistente Gruppe repliziert werden.
* *Effizienz.* Nachdem die erste Replikationsbeziehung hergestellt ist, werden nur Änderungen repliziert. Darüber hinaus bleiben Effizienzfunktionen wie Deduplizierung und Komprimierung erhalten und verringern die zu übertragende Datenmenge an einen Remote-Standort weiter.
* *Flexibilität.* Spiegelungen können vorübergehend unterbrochen werden, um das Testen von Disaster-Recovery-Verfahren zu ermöglichen. Anschließend kann die Spiegelung problemlos wiederhergestellt werden, ohne dass eine vollständige Neuspiegelung erforderlich ist. Nur die geänderten Daten müssen angewendet werden, um die Spiegelungen wieder zu synchronisieren. Die Spiegelung kann auch umgekehrt werden, um eine schnelle Resynchronisierung nach dem Zwischenfall und nach der Rückkehr des ursprünglichen Standorts möglich zu machen. Schließlich stehen Lese- und Schreibklone replizierter Daten für Test und Entwicklung zur Verfügung.


ONTAP bietet zwar mehrere verschiedene Replizierungstechnologien, die größte Flexibilität ist jedoch SnapMirror, eine asynchrone Spiegelungsoption von Volume zu Volume.

Wie bereits erwähnt, ist ein FlexVol Volume die grundlegende Managementeinheit für Snapshot-basierte Backups und SnapRestore-basierte Recovery. Ein FlexVol Volume ist außerdem die Basiseinheit für die SnapMirror-basierte Replizierung. Der erste Schritt ist die Erstellung der Basisspiegelung des Quell-Volume auf das Ziel-Volume. Nach der Initialisierung dieser Spiegelbeziehung basieren alle nachfolgenden Vorgänge allein auf der Replikation der geänderten Daten.

Aus Sicht der Recovery gelten die folgenden zentralen Werte für SnapMirror:

* SnapMirror Vorgänge lassen sich leicht verstehen und einfach automatisieren.
* Bei einer einfachen Aktualisierung eines SnapMirror Replikats müssen nur die Delta-Änderungen repliziert werden. Dies reduziert die Bandbreitenanforderungen und ermöglicht häufigere Updates.
* SnapMirror bietet hohe Granularität. Er basiert auf einfachen Volume-to-Volume-Beziehungen und ermöglicht die Erstellung von Hunderten von unabhängig gemanagten Replikaten und Replikationsintervallen. Die Replikation muss nicht eine Einheitslösung sein.
* Die Spiegelungsrichtung kann leicht umgekehrt werden, wobei die Fähigkeit erhalten bleibt, die Beziehung allein auf der Grundlage der Änderungen zu aktualisieren. Dies ermöglicht ein schnelles Failback, nachdem der primäre Standort nach einem Ausfall, wie z. B. einem Stromausfall, wieder in Betrieb genommen wurde. Nur die Änderungen müssen zurück zur Quelle synchronisiert werden.
* Spiegelungen können einfach beschädigt und effizient neu synchronisiert werden, um eine Wiederholung des Disaster Recovery-Verfahrens zu ermöglichen.
* SnapMirror, das im vollen Replizierungsmodus auf Blockebene arbeitet, repliziert nicht nur die Daten eines Volumes, sondern auch die Snapshots. Diese Funktion bietet sowohl eine Kopie der Daten als auch einen vollständigen Satz von Backups am Disaster-Recovery-Standort.


Im versionsflexiblen Modus von SnapMirror können spezifische Snapshots repliziert und unterschiedliche Aufbewahrungszeiten am primären und sekundären Standort ermöglicht werden.



== SnapMirror Synchronous

SnapMirror Synchronous (SM-S) ist eine Erweiterung von SnapMirror, die eine synchrone RPO=0-Replizierung bietet. Sie wird besonders häufig in Storage-Architekturen eingesetzt, in denen nur ein Teil der gesamten Daten eine synchrone Spiegelung erfordert.

SM-S kann in zwei leicht unterschiedlichen Modi, Sync und StrictSync, betrieben werden.

Im synchronen Modus werden Änderungen repliziert, bevor sie bestätigt werden. Dadurch wird ein RPO von Null garantiert, sofern die Replizierung betriebsbereit ist. Wenn die Änderung nicht repliziert werden kann, kann SM-S den synchronen Modus beenden und den Betrieb fortsetzen. Dies ermöglicht RPO=0 unter normalen Umständen, aber die Datenprozesse werden nicht vollständig angehalten, wenn das Replikationsziel nicht verfügbar ist.

StrictSync garantiert ein RPO=0. Ein Fehler beim Replizieren von Änderungen führt zu einem I/O-Fehler, der in der Regel zum Herunterfahren der Applikation führt.

Eine vollständige Erläuterung von SM-S finden Sie unter https://www.netapp.com/media/17174-tr4733.pdf?v=1221202075448P["TR-4733"^] Und die offizielle ONTAP-Dokumentation. Die Funktionen werden kontinuierlich mit neuen Versionen von ONTAP ergänzt.



== Konsistenzgruppen

ONTAP ermöglicht die Erstellung von Konsistenzgruppen-Snapshots. Ab 9.13.1 kann ONTAP Gruppen von Volumes (wobei zu beachten ist, dass ein Volume in der ONTAP-Terminologie keine LUN, sondern ein Management-Container aus einer oder mehreren Dateien oder LUNs ist) als konsistente Gruppe replizieren.

Die SnapMirror-Replizierung und die Unterbrechung der CG SnapMirror-Beziehung gewährleisten die Konsistenz über Volumes hinweg, und SnapMirror Synchronous und SnapMirror Business Continuity bewahren beide die Konsistenz über einzelne Volumes hinweg.

Das Ergebnis: Sie können einen Datensatz mit mehreren Volumes replizieren und sicherstellen, dass alle Volumes Cross-konsistent sind. Dadurch werden u. a. die Spiegelungen unterbrochen und DR-Vorgänge unterbrochen, ohne dass zusätzliche Schritte zur Applikations- oder Datenbank-Recovery nötig sind.



== MetroCluster und SyncMirror

MetroCluster ist außerdem eine Lösung für synchrone Replizierung für umfangreiche geschäftskritische Workloads. Die Replizierung basiert auf SyncMirror. SyncMirror erstellt auf der einfachsten Ebene zwei vollständige Sätze RAID-geschützter Daten an zwei verschiedenen Orten. Sie könnten sich in angrenzenden Räumen innerhalb eines Datacenters oder sogar viele Kilometer voneinander entfernt befinden.

SyncMirror ist vollständig in ONTAP integriert und wird knapp über dem RAID Level ausgeführt. Daher funktionieren alle üblichen ONTAP-Funktionen wie Snapshot Kopien, SnapRestore und NetApp FlexClone nahtlos. Es handelt sich noch immer um ONTAP und umfasst nur eine zusätzliche Ebene der synchronen Datenspiegelung.

Eine Sammlung von ONTAP Controllern, die SyncMirror-Daten managen, wird als NetApp MetroCluster-Konfiguration bezeichnet. Der Hauptzweck von MetroCluster ist es, Hochverfügbarkeit auf synchron gespiegelte Daten in einer Vielzahl von typischen und Disaster-Recovery-Ausfallszenarien zu bieten.

Die Datensicherung mit MetroCluster und SyncMirror hat folgende zentrale Vorteile:

* Im normalen Betrieb ermöglicht SyncMirror standortübergreifendes, synchrones Spiegeln. Ein Schreibvorgang wird erst dann bestätigt, wenn er auf nicht-flüchtigen Medien an beiden Standorten vorhanden ist.
* Wenn die Verbindung zwischen Standorten ausfällt, wechselt SyncMirror automatisch in den asynchronen Modus, damit der primäre Standort Daten bereitstellt, bis die Verbindung wiederhergestellt ist. Bei einer Wiederherstellung ermöglicht es eine schnelle Neusynchronisierung, indem die am primären Standort angesammelten Änderungen effizient aktualisiert werden. Eine vollständige Neuinitialisierung ist nicht erforderlich.


SnapMirror ist zudem vollständig mit SyncMirror-basierten Systemen kompatibel. Beispielsweise kann eine primäre Datenbank auf einem MetroCluster Cluster ausgeführt werden, das über zwei geografische Standorte verteilt ist. Diese Datenbank kann Backups auch als langfristige Archive an einem dritten Standort oder zur Erstellung von Klonen in einer DevOps-Umgebung replizieren.
