---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-settings.html 
keywords: VMware,vSphere,ESXi,settings,NFS,iSCSI,FC,FCP 
summary: In diesem Dokument werden die empfohlenen Speicher- und Netzwerkeinstellungen kategorisiert und aufgelistet. 
---
= Empfohlene ESXi Host-Einstellungen und andere ONTAP Einstellungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp hat optimale ESXi Host-Einstellungen für NFS- und Blockprotokolle entwickelt. Des Weiteren finden Sie spezielle Anleitungen zu Multipathing- und HBA-Zeitüberschreitungseinstellungen, um ein angemessenes Verhalten gegenüber ONTAP auf der Grundlage interner Tests von NetApp und VMware zu gewährleisten.

Diese Werte lassen sich mit den ONTAP-Tools für VMware vSphere problemlos einstellen: Scrollen Sie auf der Übersichtsseite der ONTAP-Tools nach unten und klicken Sie im Portlet „ESXi-Host-Compliance“ auf empfohlene Einstellungen anwenden.

Im Folgenden finden Sie die empfohlenen Host-Einstellungen für alle derzeit unterstützten Versionen von ONTAP.

|===
| *Hosteinstellung* | *Von NetApp empfohlener Wert* | *Neustart Erforderlich* 


3+| *ESXi Advanced Configuration* 


| VMFS3.HardwareAcceleratLocking | Standard beibehalten (1) | Nein 


| VMFS3.EnableBlockDelete | Behalten Sie die Standardeinstellung (0) bei, können sie jedoch bei Bedarf geändert werden. Weitere Informationen finden Sie unter link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-provisioning-and-space-reclamation-in-vsphere/storage-space-reclamation-in-vsphere/space-reclamation-for-guest-operating-systems.html["Speicherplatzrückgewinnung für virtuelle VMFS5-Maschinen"] | Nein 


| VMFS3.EnableVMFS6Entmappen | Behalten Sie die Standardeinstellung (1) bei. Weitere Informationen finden Sie unter link:https://www.vmware.com/docs/vmw-vmware-vsphere-apis-array-integration-vaai["VMware vSphere APIs – Array-Integration (VAAI)"] | Nein 


3+| *NFS-Einstellungen* 


| NewSyncInterval | Wenn Sie vSphere CSI für Kubernetes nicht verwenden, setzen Sie per ein https://knowledge.broadcom.com/external/article/386364/reducing-excessive-vsan-cnssync-warnings.html["VMware KB 386364"^] | Nein 


| NET.TcpipHeapSize | VSphere 6.0 oder höher: Auf 32 einstellen.
Alle anderen NFS-Konfigurationen: Auf 30 einstellen | Ja. 


| NET.TcpipHeapMax | Sind die meisten vSphere 6.X Versionen auf 512 MB eingestellt.
Für 6.5U3, 6.7U3 und 7.0 oder höher auf Standard (1024 MB) gesetzt. | Ja. 


| MaxVolumes: NFS | VSphere 6.0 oder höher: Auf 256 einstellen
Alle anderen NFS-Konfigurationen auf 64 eingestellt. | Nein 


| NFS41.MaxVolumes | VSphere 6.0 oder höher: Auf 256 einstellen. | Nein 


| NFS.MaxQueueDepth^1^ | VSphere 6.0 oder höher: Auf 128 einstellen | Ja. 


| NFS.HeartbeatMaxFailures | Alle NFS-Konfigurationen: Auf 10 einstellen | Nein 


| HeartbeatFrequency NFS.HeartbeatFrequency | Alle NFS-Konfigurationen: Auf 12 einstellen | Nein 


| HeartbeatTimeout NFS.HeartbeatTimeout | Alle NFS-Konfigurationen: Auf 5 einstellen. | Nein 


| SunRPC.MaxConnPerIP | vSphere 7.0 bis 8.0, auf 128 eingestellt.  Diese Einstellung wird in ESXi-Versionen nach 8.0 ignoriert. | Nein 


3+| *FC/FCoE-Einstellungen* 


| Pfadauswahl-Richtlinie | Wenn FC-Pfade mit ALUA verwendet werden: Auf RR (Round Robin) einstellen. Alle anderen Konfigurationen: Auf FIXED einstellen.
Wenn Sie diesen Wert auf RR einstellen, ist für alle aktiven/optimierten Pfade ein besserer Lastausgleich möglich.
Der Wert FIXED wird für ältere Konfigurationen ohne ALUA verwendet und verhindert Proxy-I/O-Vorgänge Er trägt also dazu bei, dass I/O-Vorgänge bei einem HA-Paar in einer Umgebung, in der Data ONTAP im 7-Mode ausgeführt wird, nicht auf den anderen Node verlagert werden | Nein 


| Disk.QFullSampleSize | Alle Konfigurationen: Auf 32 einstellen.
Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert. | Nein 


| Disk.QFullThreshold | Alle Konfigurationen: Auf 8 einstellen.
Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert. | Nein 


| Emulex FC-HBA-Zeitüberschreitungen | Standardwert verwenden. | Nein 


| QLogic FC-HBA-Zeitüberschreitungen | Standardwert verwenden. | Nein 


3+| *ISCSI-Einstellungen* 


| Pfadauswahl-Richtlinie | Alle iSCSI-Pfade: Auf RR (Round Robin) einstellen.
Wenn Sie diesen Wert auf RR einstellen, ist für alle aktiven/optimierten Pfade ein besserer Lastausgleich möglich. | Nein 


| Disk.QFullSampleSize | Alle Konfigurationen: Auf 32 einstellen.
Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert | Nein 


| Disk.QFullThreshold | Alle Konfigurationen: Auf 8 einstellen.
Durch die Festlegung dieses Wertes werden I/O-Fehler verhindert. | Nein 
|===

NOTE: Die erweiterte NFS-Konfigurationsoption MaxQueueDepth funktioniert möglicherweise nicht wie vorgesehen, wenn VMware vSphere ESXi 7.0.1 und VMware vSphere ESXi 7.0.2 verwendet werden. Referenz link:https://kb.vmware.com/s/article/86331?lang=en_US["VMware KB 86331"] für weitere Informationen.

ONTAP-Tools legen beim Erstellen von ONTAP FlexVol Volumes und LUNs bestimmte Standardeinstellungen fest:

|===


| *ONTAP-Tool* | *Standardeinstellung* 


| Snapshot-Reserve (-percent-Snapshot-space) | 0 


| Fraktionale Reserve (-fractional-Reserve) | 0 


| Aktualisierung der Zugriffszeit (-atime-Update) | Falsch 


| Minimales Vorauslesen (-min-readahead) | Falsch 


| Geplante Snapshots | Keine 


| Storage-Effizienz | Aktiviert 


| Volume-Garantie | Keine (Thin Provisioning) 


| Automatische Volumengröße | Vergrößern_verkleinern 


| LUN-Speicherplatzreservierung | Deaktiviert 


| Zuweisung von LUN-Speicherplatz | Aktiviert 
|===


== Multipath-Einstellungen für die Performance

Obwohl NetApp derzeit nicht durch verfügbare ONTAP-Tools konfiguriert ist, empfiehlt es folgende Konfigurationsoptionen:

* Wenn Sie Nicht- ASA -Systeme in Hochleistungsumgebungen verwenden oder die Leistung mit einem einzelnen LUN-Datenspeicher testen, sollten Sie die Lastausgleichseinstellung der Round-Robin-Pfadauswahlrichtlinie (VMW_PSP_RR) von der IOPS-Standardeinstellung von 1000 auf den Wert 1 ändern.  Sehenlink:https://knowledge.broadcom.com/external/article?legacyId=2069356["VMware KB 2069356"^] für weitere Informationen.
* In vSphere 6.7 Update 1 hat VMware einen neuen Latenz-Lastausgleichsmechanismus für das Round Robin PSP eingeführt.  Die Latenzoption ist jetzt auch bei Verwendung des HPP (High Performance Plugin) mit NVMe-Namespaces und mit vSphere 8.0u2 und höher, über iSCSI und FCP verbundenen LUNs verfügbar.  Die neue Option berücksichtigt die E/A-Bandbreite und die Pfadlatenz bei der Auswahl des optimalen Pfads für die E/A.  NetApp empfiehlt die Verwendung der Latenzoption in Umgebungen mit nicht äquivalenter Pfadkonnektivität, beispielsweise in Fällen, in denen auf einem Pfad mehr Netzwerk-Hops vorhanden sind als auf einem anderen, oder bei Verwendung eines NetApp ASA -Systems.  Sehen https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts.html#GUID-1940AE9E-04CF-40BE-BB71-398621F0642E-en["Standardparameter für Latenzrunde Robin ändern"^] für weitere Informationen.




== Zusätzliche Dokumentation

Für FCP und iSCSI mit vSphere 7 finden Sie weitere Informationen unter link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["Verwenden Sie VMware vSphere 7.x mit ONTAP"^] für FCP und iSCSI mit vSphere 8. Weitere Informationen finden Sie unter  für NVMe-of mit vSphere 7. Weitere Details finden Sie unter link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Verwenden Sie VMware vSphere 8.x mit ONTAP"^]für NVMe-of mit vSphere 8. Weitere Details finden Sie unter link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["Für NVMe-of finden Sie weitere Details unter NVMe-of Host Configuration for ESXi 7.x with ONTAP"^]link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Für NVMe-of finden Sie weitere Details unter NVMe-of Host Configuration for ESXi 8.x with ONTAP"^]
