---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-cloud_migration_backup.html 
keywords: Data protection, Space reclamation, VM and datastore cloning, Storage efficiency, thin provisioning, QoS, SIOC, Storage Distributed Resource Scheduler, DRS, Active IQ Unified Manager, Encryption 
summary: ONTAP bietet umfassende Unterstützung für die Hybrid Cloud. 
---
= Cloud-Migration und -Backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Eine weitere Stärke von ONTAP ist die umfassende Unterstützung für die Hybrid Cloud, bei der Systeme in Ihrer Private Cloud vor Ort mit Public-Cloud-Funktionen vereint werden. Im Folgenden sind einige NetApp Cloud-Lösungen aufgeführt, die gemeinsam mit vSphere verwendet werden können:

* *Angebote von Erstanbietern.* Amazon FSx for NetApp ONTAP, Google Cloud NetApp Volumes und Azure NetApp Files bieten leistungsstarke, multiprotokollverwaltete Speicherdienste in den führenden öffentlichen Cloud-Umgebungen. Sie können direkt von VMware Cloud on AWS (VMC on AWS), Azure VMware Solution (AVS) und Google Cloud VMware Engine (GCVE) als Datenspeicher oder Speicher für Gastbetriebssysteme (GOS) und Compute-Instanzen verwendet werden.
* *Cloud Volumes ONTAP.* die NetApp Cloud Volumes ONTAP Datenmanagement-Software bietet Kontrolle, Schutz, Flexibilität und Effizienz für Ihre Unternehmensdaten in der gewünschten Cloud. Cloud Volumes ONTAP ist eine Cloud-native Datenmanagement-Software auf der Basis von ONTAP Storage. Nutzen Sie diese Technologie zusammen mit Cloud Manager, um Cloud Volumes ONTAP Instanzen gemeinsam mit Ihren lokalen ONTAP Systemen zu implementieren und zu managen. Nutzen Sie erweiterte NAS- und iSCSI SAN-Funktionen mit einheitlichem Datenmanagement einschließlich Snapshots und SnapMirror Replizierung.
* *Cloud-Dienste.* Verwenden Sie NetApp Backup and Recovery oder SnapMirror Cloud, um Daten von lokalen Systemen mithilfe von öffentlichem Cloud-Speicher zu schützen. Cloud Sync unterstützt Sie bei der Migration und Synchronisierung Ihrer Daten zwischen NAS, Objektspeichern und Cloud Volumes Service Speicher. NetApp Disaster Recovery bietet eine kostengünstige und effiziente Lösung zur Nutzung von NetApp -Technologien als Grundlage für eine robuste und leistungsfähige Disaster Recovery-Lösung für DR in die Cloud, DR vor Ort und vor Ort zu vor Ort.
* *FabricPool.* FabricPool bietet schnelles und einfaches Tiering für ONTAP Daten. Selten genutzte, „kalte“ Blöcke können zu einem Objektspeicher in Public Clouds oder zu einem privaten StorageGRID Objektspeicher migriert werden und beim erneuten Zugriff auf die ONTAP-Daten automatisch wieder abgerufen werden. Alternativ können Sie die Objekt-Tier als dritte Schutzebene für Daten verwenden, die bereits von SnapVault gemanagt werden. Dieser Ansatz kann Ihnen ermöglichen https://www.linkedin.com/pulse/rethink-vmware-backup-again-keith-aasen/["Speichern Sie mehr Snapshots Ihrer VMs"^] Auf primären und/oder sekundären ONTAP-Storage-Systemen.
* *ONTAP Select.* mit softwaredefiniertem NetApp Storage erweitern Sie Ihre Private Cloud über das Internet auf Remote-Einrichtungen und Niederlassungen, in denen Sie ONTAP Select zur Unterstützung von Block- und Fileservices sowie denselben vSphere Datenmanagementfunktionen nutzen können, die Sie in Ihrem Unternehmens-Datacenter haben.


Berücksichtigen Sie beim Entwerfen Ihrer VM-basierten Anwendungen die zukünftige Cloud-Mobilität. Anstatt beispielsweise Anwendungs- und Datendateien zusammen zu platzieren, verwenden Sie einen separaten LUN- oder NFS-Export für die Daten. Dadurch können Sie die VM und die Daten separat zu Cloud-Diensten migrieren.

In den folgenden Ressourcen erhalten Sie ausführliche Informationen zu weiteren Sicherheitsthemen.

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP-Dokumentation"]
* link:https://docs.netapp.com/us-en/ontap-select/["ONTAP Select-Dokumentation"]
* link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Dokumentation zu Sicherung und Wiederherstellung"]
* link:https://docs.netapp.com/us-en/data-services-disaster-recovery/index.html["Disaster Recovery-Dokumentation"]
* link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSX für NetApp ONTAP"]
* link:https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud auf AWS"]
* link:https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction["Was ist Azure NetApp Files?
"]
* link:https://azure.microsoft.com/en-us/products/azure-vmware/["Azure VMware Lösung"]
* link:https://cloud.google.com/vmware-engine["Google Cloud VMware Engine"]
* link:https://cloud.google.com/netapp/volumes/docs/discover/overview["Was ist Google Cloud NetApp Volumes?"]

