---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'Die ONTAP-Lösung für VMware Live Site Recovery (VLSR) und Site Recovery Manager (SRM)' 
---
= VMware Live-Site Recovery mit ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP ist seit der Einführung von ESX in modernen Rechenzentren vor mehr als zwei Jahrzehnten eine führende Speicherlösung für VMware vSphere und in jüngerer Zeit für Cloud Foundation.  NetApp führt weiterhin innovative Systeme ein, beispielsweise die neueste Generation der ASA A-Serie zusammen mit Funktionen wie SnapMirror Active Sync.  Diese Fortschritte vereinfachen die Verwaltung, verbessern die Ausfallsicherheit und senken die Gesamtbetriebskosten (TCO) Ihrer IT-Infrastruktur.

Dieses Dokument stellt die ONTAP -Lösung für VMware Live Site Recovery (VLSR), früher bekannt als Site Recovery Manager (SRM), die branchenführende Disaster Recovery (DR)-Software von VMware, vor, einschließlich der neuesten Produktinformationen und Best Practices zur Optimierung der Bereitstellung, Risikominderung und Vereinfachung der laufenden Verwaltung.


NOTE: Diese Dokumentation ersetzt den zuvor veröffentlichten technischen Bericht _TR-4900: VMware Site Recovery Manager mit ONTAP_

Andere Dokumente wie Leitfäden und Kompatibilitäts-Tools werden durch Best Practices ergänzt. Sie werden basierend auf Labortests und umfassenden praktischen Erfahrungen der NetApp Ingenieure und Kunden entwickelt. In einigen Fällen passen empfohlene Best Practices möglicherweise nicht zu Ihrer Umgebung. Sie sind jedoch im Allgemeinen die einfachsten Lösungen, die die Anforderungen der meisten Kunden erfüllen.

Der Schwerpunkt dieses Dokuments liegt auf den Funktionen der neuesten Versionen von ONTAP 9, die in Verbindung mit ONTAP-Tools für VMware vSphere 10.4 (einschließlich NetApp Storage Replication Adapter [SRA] und VASA Provider [VP]) sowie VMware Live Site Recovery 9 verwendet werden.



== Vorteile von ONTAP mit VLSR oder SRM

NetApp Datenverwaltungsplattformen auf Basis von ONTAP gehören zu den am weitesten verbreiteten Speicherlösungen für VLSR.  Die Gründe dafür sind vielfältig: Eine sichere, leistungsstarke Datenverwaltungsplattform mit einheitlichem Protokoll (NAS und SAN zusammen), die branchenführende Speichereffizienz, Mandantenfähigkeit, Qualitätskontrollen, Datenschutz mit platzsparenden Snapshots und Replikation mit SnapMirror bietet.  Alle nutzen die native Hybrid-Multi-Cloud-Integration zum Schutz von VMware-Workloads und eine Vielzahl von Automatisierungs- und Orchestrierungstools, die Ihnen jederzeit zur Verfügung stehen.

Wenn Sie SnapMirror für die Array-basierte Replikation verwenden, profitieren Sie von einer der bewährtesten und ausgereiftesten Technologien von ONTAP.  SnapMirror bietet Ihnen den Vorteil sicherer und hocheffizienter Datenübertragungen, da nur geänderte Dateisystemblöcke kopiert werden, nicht ganze VMs oder Datenspeicher.  Sogar diese Blöcke profitieren von Platzeinsparungen wie Deduplizierung, Komprimierung und Verdichtung.  Moderne ONTAP -Systeme verwenden jetzt das versionsunabhängige SnapMirror, sodass Sie Ihre Quell- und Zielcluster flexibel auswählen können.  SnapMirror hat sich tatsächlich zu einem der leistungsstärksten verfügbaren Tools für die Notfallwiederherstellung entwickelt.

Unabhängig davon, ob Sie herkömmliche NFS-, iSCSI- oder Fibre Channel-Datenspeicher verwenden (jetzt mit Unterstützung für vVols Datenspeicher), bietet VLSR ein robustes First-Party-Angebot, das die besten ONTAP Funktionen für die Notfallwiederherstellung oder die Planung und Orchestrierung der Datencenter-Migration nutzt.



== Wie VLSR ONTAP 9 nutzt

VLSR nutzt die erweiterten Datenmanagement-Technologien von ONTAP Systemen. Die Integration mit ONTAP Tools für VMware vSphere, einer virtuellen Appliance mit drei Hauptkomponenten:

* Das vCenter Plug-in der ONTAP Tools, früher als Virtual Storage Console (VSC) bekannt, vereinfacht das Storage Management und die Effizienzfunktionen, erhöht die Verfügbarkeit und senkt die Storage-Kosten und den Betriebsaufwand, sowohl bei SAN als auch bei NAS. Dieses Plug-in nutzt Best Practices für die Bereitstellung von Datastores und optimiert ESXi Hosteinstellungen für NFS- und Block-Storage-Umgebungen. Wegen all dieser Vorteile empfiehlt NetApp bei der Nutzung von vSphere bei Systemen mit ONTAP dieses Plug-in.
* Die ONTAP Tools VASA Provider unterstützen das VMware vStorage APIs for Storage Awareness (VASA) Framework. VASA Provider verbindet vCenter Server mit ONTAP und erleichtert so die Bereitstellung und das Monitoring von VM-Storage. Auf diese Weise wurden VMware Virtual Volumes (VVols) unterstützt und das Management von VM-Storage-Richtlinien sowie die VVols-Performance für einzelne VMs wurde ermöglicht. Außerdem gibt es Alarme zur Überwachung der Kapazität und der Konformität mit den Profilen.
* SRA wird zusammen mit VLSR eingesetzt, um die Replizierung von VM-Daten zwischen Produktions- und Disaster-Recovery-Standorten bei herkömmlichen VMFS- und NFS-Datenspeichern sowie zum unterbrechungsfreien Testen von DR-Replikaten zu managen. Diese Software hilft bei der Automatisierung der Erkennungs-, Recovery- und Sicherungsaufgaben. Es enthält sowohl eine SRA-Server-Appliance als auch SRA-Adapter für den Windows SRM-Server und die VLSR-Appliance.


Nachdem Sie die SRA-Adapter auf dem VLSR-Server zum Schutz von Nicht-vVols-Datenspeichern installiert und konfiguriert haben, können Sie mit der Konfiguration Ihrer vSphere-Umgebung für die Notfallwiederherstellung beginnen.

SRA bietet eine Befehls- und Kontrollschnittstelle für den VLSR-Server zur Verwaltung der ONTAP FlexVol-Volumes, die Ihre virtuellen VMware-Maschinen (VMs) enthalten, sowie zur Sicherung der SnapMirror-Replikation.

VLSR kann Ihren DR-Plan unterbrechungsfrei testen, indem es die proprietäre FlexClone -Technologie von NetApp verwendet, um nahezu sofortige Klone Ihrer geschützten Datenspeicher an Ihrem DR-Standort zu erstellen.  VLSR erstellt eine Sandbox zum sicheren Testen, sodass Ihr Unternehmen und Ihre Kunden im Falle einer echten Katastrophe geschützt sind. So können Sie darauf vertrauen, dass Ihr Unternehmen im Katastrophenfall ein Failover durchführen kann.

Bei einem echten Ausfall oder sogar einer geplanten Migration können Sie mit VLSR alle Last-Minute-Änderungen am Datensatz über ein letztes SnapMirror Update senden (sofern Sie dies tun). Dann wird die Spiegelung unterbrochen und der Datenspeicher wird Ihren DR-Hosts gemountet. An diesem Punkt können Ihre VMs automatisch in beliebiger Reihenfolge gemäß Ihrer vorab geplanten Strategie hochgefahren werden.


NOTE: Mit ONTAP Systemen können Sie SVMs zwecks SnapMirror Replizierung im selben Cluster kombinieren, jedoch wurde dieses Szenario nicht mit VLSR getestet und zertifiziert. Daher wird empfohlen, bei Verwendung von VLSR nur SVMs aus unterschiedlichen Clustern zu verwenden.



== VLSR mit ONTAP und anderen Anwendungsfällen: Hybrid Cloud und Migration

Durch die Integration Ihrer VLSR-Bereitstellung mit den erweiterten Datenverwaltungsfunktionen von ONTAP können Sie im Vergleich zu lokalen Speicheroptionen eine deutlich verbesserte Skalierbarkeit und Leistung erzielen. Darüber hinaus bietet es die Flexibilität der Hybrid Cloud. Mit der Hybrid Cloud können Sie Geld sparen, indem Sie ungenutzte Datenblöcke von Ihrem Hochleistungs-Array mithilfe von FabricPool auf Ihren bevorzugten Hyperscaler auslagern. Dabei kann es sich um einen lokalen S3-Speicher wie NetApp StorageGRID handeln. Sie können SnapMirror auch für Edge-basierte Systeme mit softwaredefiniertem ONTAP Select oder Cloud-basierter DR verwenden, indem Sie https://www.equinix.com/partners/netapp["NetApp Storage auf Equinix Metal"^]oder andere gehostete ONTAP -Dienste.

Anschließend könnten Sie dank FlexClone ein Test-Failover innerhalb des Datacenters eines Cloud-Service-Providers durchführen, bei einem Storage-Platzbedarf von nahezu null. Der Schutz Ihres Unternehmens ist jetzt günstiger als je zuvor.

Mit VLSR können auch geplante Migrationen durchgeführt werden, indem VMs mit SnapMirror effizient von einem Datacenter in ein anderes oder sogar innerhalb desselben Datacenters übertragen werden, unabhängig davon, ob es sich um Ihr eigenes Datacenter oder über eine beliebige Anzahl an Service Providern von NetApp Partnern handelt.
