---
sidebar: sidebar 
permalink: vmware/vmware-security-snapcenter.html 
keywords: WP-7355, security, snapcenter, treat modeling, dast, vulnerability scanning, penetration testing 
summary:  
---
= SnapCenter Plug-in VMware vSphere
:allow-uri-read: 


[role="lead"]
Das NetApp SnapCenter Plug-in für VMware vSphere nutzt folgende sichere Entwicklungsaktivitäten:

* *Threat Modeling.* der Zweck der Bedrohungsmodellierung ist es, Sicherheitslücken in einem Feature, einer Komponente oder einem Produkt frühzeitig im Lebenszyklus der Softwareentwicklung zu entdecken. Ein Bedrohungsmodell ist eine strukturierte Darstellung aller Informationen, die die Sicherheit einer Anwendung beeinflussen. Im Wesentlichen ist es ein Blick auf die Anwendung und ihre Umgebung durch die Linsen der Sicherheit.
* *Dynamic Application Security Testing (DAST).* Technologien, die entwickelt wurden, um gefährdete Bedingungen für Anwendungen in ihrem laufenden Zustand zu erkennen. DAST testet die freigesetzten HTTP- und HTML-Schnittstellen von Web-enable-Anwendungen.
* *Codewährung von Drittanbietern.* im Rahmen der Entwicklung von Software und der Verwendung von Open-Source-Software (OSS) ist es wichtig, Sicherheitslücken zu beheben, die mit OSS verbunden sein könnten, die in Ihr Produkt integriert wurden. Dies ist ein kontinuierlicher Aufwand, da bei der Version der OSS-Komponente eine neu entdeckte Sicherheitsanfälligkeit jederzeit gemeldet wird.
* *Schwachstellenscans.* Zweck der Schwachstellenanalyse ist es, häufige und bekannte Sicherheitslücken in NetApp Produkten zu erkennen, bevor diese bei den Kunden freigegeben werden.
* *Penetrationstest.* Penetrationstest ist der Prozess, um ein System, eine Web-Anwendung oder ein Netzwerk zu evaluieren, um Sicherheitslücken zu finden, die von einem Angreifer ausgenutzt werden könnten. Penetrationstests (Penetrationstests) bei NetApp werden von einer Gruppe genehmigter und vertrauenswürdiger Drittanbieter durchgeführt. Ihr Testumfang umfasst die Einleitung von Angriffen gegen eine Anwendung oder Software wie feindliche Eindringlinge oder Hacker mit ausgereiften Exploitationsmethoden oder -Tools.
* *Product Security Incident Response Aktivität.* Sicherheitslücken werden sowohl intern als auch extern entdeckt und können ein ernsthaftes Risiko für NetAppâ €™s Ruf darstellen, wenn sie nicht rechtzeitig angesprochen werden. Zur Erleichterung dieses Prozesses meldet ein PSIRT (Product Security Incident Response Team) die Sicherheitsanfälligkeiten und verfolgt diese.




== Produktsicherheitsfunktionen

Das NetApp SnapCenter Plug-in für VMware vSphere umfasst die folgenden Sicherheitsfunktionen in jeder Version:

* *Eingeschränkter Shell-Zugriff.* SSH ist standardmäßig deaktiviert, und einmalige Anmeldungen sind nur erlaubt, wenn sie über die VM-Konsole aktiviert sind.
* *Zugangswarnung im Anmeldebanner.* das folgende Anmeldebanner wird angezeigt, nachdem der Benutzer einen Benutzernamen in die Anmeldeaufforderung eingegeben hat:
+
*WARNUNG:* der unerlaubte Zugriff auf dieses System ist verboten und wird gesetzlich verfolgt. Durch den Zugriff auf dieses System erklären Sie sich damit einverstanden, dass Ihre Maßnahmen überwacht werden können, wenn eine unbefugte Nutzung vermutet wird.

+
Nachdem der Benutzer die Anmeldung über den SSH-Kanal abgeschlossen hat, wird die folgende Ausgabe angezeigt:



....
Linux vsc1 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
....
* *Rollenbasierte Zugriffssteuerung (Role Based Access Control, RBAC).* NetApp ONTAP Tools verfügen über zwei Arten von RBAC-Steuerelementen:
+
** Native vCenter Server-Berechtigungen.
** Spezifische Berechtigungen für VMware vCenter Plug-in Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_role_based_access_control.html["Rollenbasierte Zugriffssteuerung (Role Based Access Control, RBAC)"^].


* *Verschlüsselte Kommunikationskanäle.* Alle externen Kommunikation erfolgt über HTTPS mit TLS.
* *Minimal Port Exposure.* nur die benötigten Ports sind an der Firewall geöffnet.


Die folgende Tabelle enthält die Details zum offenen Anschluss.

|===
| TCP v4/v6-Portnummer | Funktion 


| 8144 | HTTPS-Verbindungen für REST-API 


| 8080 | HTTPS-Verbindungen für OVA GUI 


| 22 | SSH (standardmäßig deaktiviert) 


| 3306 | MySQL (nur interne Verbindungen; externe Verbindungen standardmäßig deaktiviert) 


| 443 | Nginx (Datensicherungsservices) 
|===
* *Unterstützung für Zertifizierungsstelle (CA) signierte Zertifikate.* SnapCenter Plug-in für VMware vSphere unterstützt die Funktion von CA signierten Zertifikaten. Siehe https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_and_or_import_an_SSL_certificate_to_SnapCenter_Plug-in_for_VMware_vSphere["Erstellen und/oder Importieren eines SSL-Zertifikats in das SnapCenter Plug-in für VMware vSphere (SCV)"^].
* *Passwortrichtlinien.* die folgenden Kennwortrichtlinien sind in Kraft:
+
** Passwörter werden nicht in Protokolldateien protokolliert.
** Passwörter werden nicht im Klartext kommuniziert.
** Während des Installationsvorgangs selbst werden Passwörter konfiguriert.
** Alle Anmeldeinformationen werden mit SHA256 Hashing gespeichert.


* *Basis Betriebssystem-Image.* das Produkt wird mit Debian Base OS für OVA ausgeliefert, mit eingeschränktem Zugriff und Shell-Zugriff. So wird die Angriffsfläche reduziert. Jedes Betriebssystem der SnapCenter Version wird mit den neuesten Sicherheits-Patches aktualisiert, die für maximale Sicherheit verfügbar sind.


NetApp entwickelt Softwarefunktionen und Sicherheits-Patches zu den SnapCenter Plug-ins für die VMware vSphere Appliance und gibt sie anschließend dem Kunden als gebündelte Software-Plattform frei. Da diese Appliances bestimmte Linux Unterbetriebssystem-Abhängigkeiten sowie unsere proprietäre Software umfassen, empfiehlt NetApp, am Unterbetriebssystem keine Änderungen vorzunehmen, da dies ein hohes Potenzial hat, die NetApp Appliance zu beeinträchtigen. Dies könnte sich darauf auswirken, inwieweit NetApp die Appliance unterstützt. NetApp empfiehlt, unsere neueste Code-Version für Appliances zu testen und zu implementieren, da sie veröffentlicht werden, um sicherheitsbezogene Probleme zu patchen.
