---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-flexgroups.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: Auf dieser Seite werden die Best Practices zur Implementierung einer NetApp ONTAP Storage-Lösung in einer VMware vSphere Umgebung beschrieben. 
---
= Flexgroups
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 9.8 adds support for FlexGroup datastores in vSphere
:revdate: along with the ONTAP tools for VMware vSphere 9.8 release.


FlexGroup vereinfacht die Erstellung großer Datastores und erstellt automatisch eine Reihe von zusammengehörigen Volumes, um die maximale Performance eines ONTAP Systems zu erreichen. Nutzen Sie FlexGroup mit vSphere für einen einzelnen, skalierbaren vSphere Datastore, der die Leistungsfähigkeit eines vollständigen ONTAP-Clusters bietet.

Neben umfangreichen Systemtests mit vSphere Workloads bietet ONTAP 9.8 auch einen neuen Offload-Mechanismus für FlexGroup Datastores. Hierbei wird eine verbesserte Kopier-Engine verwendet, um Dateien zwischen den Komponenten im Hintergrund zu kopieren, während der Zugriff auf Quelle und Ziel möglich ist. Mehrere Kopien verwenden sofort verfügbare, platzsparende Datei-Klone in einer Komponente, wenn diese je nach Skalierung benötigt werden.

ONTAP 9.8 bietet darüber hinaus neue dateibasierte Performance-Metriken (IOPS, Durchsatz und Latenz) für FlexGroup-Dateien. Diese Kennzahlen können Sie auch in den ONTAP Tools für VMware vSphere Dashboard- und VM-Berichten ansehen. Die ONTAP Tools für VMware vSphere Plug-in ermöglichen Ihnen darüber hinaus die Festlegung von QoS-Regeln (Quality of Service) über eine Kombination aus dem Maximum und/oder dem Minimum von IOPS. Diese können über alle VMs in einem Datenspeicher oder individuell für bestimmte VMs hinweg festgelegt werden.

Im Folgenden finden Sie einige weitere NetApp Best Practices:

* Nutzen Sie die Standardeinstellungen für die FlexGroup-Bereitstellung. Es empfiehlt sich zwar ONTAP-Tools für VMware vSphere, da sie die FlexGroup in vSphere erstellen und gemountet werden. Zudem ist ONTAP System Manager oder die Befehlszeile kann für spezielle Anforderungen verwendet werden. Verwenden Sie dann selbst die Standardwerte wie die Anzahl der zusammengehörigen Mitglieder pro Node, da dies bei vSphere getestet wurde.
* Beachten Sie bei der Dimensionierung eines FlexGroup-Datenspeichers, dass die FlexGroup aus mehreren kleineren FlexVol-Volumes besteht, die einen größeren Namespace erstellen. Daher muss die Größe des Datenspeichers bei der größten Virtual Machine mindestens das Achtfache betragen. Wenn Sie beispielsweise eine 6-TB-VM in Ihrer Umgebung haben, geben Sie der FlexGroup-Datenspeicher die Größe nicht kleiner als 48 TB an.
* Erlauben Sie FlexGroup, den Datenspeicherplatz zu managen. Autosize und Elastic Sizing wurden mit vSphere Datastores getestet. Sollte der Datenspeicher annähernd die volle Kapazität erhalten, verwenden Sie ONTAP Tools für VMware vSphere oder ein anderes Tool, um die Größe des FlexGroup Volume zu ändern. Bei FlexGroup werden Kapazität und Inodes über die Komponenten hinweg ausgeglichen. So werden die Dateien in einem Ordner (VM) nach Möglichkeit der Kapazität auf dieselbe Komponente priorisiert.
* VMware und NetApp unterstützen derzeit keinen gemeinsamen Ansatz für Multipath-Netzwerke. Bei NFSv4.1 unterstützt NetApp pNFS, während VMware das Session-Trunking unterstützt. NFSv3 unterstützt nicht mehrere physische Pfade zu einem Volume. Bei FlexGroup mit ONTAP 9.8 empfehlen wir, die ONTAP-Tools für VMware vSphere beim Single Mount zu überlassen, da die Auswirkungen des indirekten Zugriffs in der Regel minimal (Mikrosekunden) sind. Es ist möglich, Round-Robin-DNS zu verwenden, um ESXi Hosts auf verschiedenen Nodes im FlexGroup über LIFs zu verteilen, allerdings müsste die FlexGroup ohne ONTAP-Tools für VMware vSphere erstellt und gemountet werden. Dann wären die Leistungsmanagementfunktionen nicht verfügbar.
* Die Unterstützung für FlexGroup vSphere Datastores wurde mit Version 9.8 auf bis zu 1500 VMs getestet.
* Nutzen Sie das NFS-Plug-in für VMware VAAI für den Offloaded Data Transfer. Beachten Sie, dass ONTAP während der Erweiterung des Klonens in einem FlexGroup Datastore keine wesentlichen Performance-Vorteile bietet gegenüber ESXi Hostkopien, wenn VMs zwischen FlexVol- und/oder FlexGroup-Volumes kopiert werden.
* Verwenden Sie ONTAP Tools für VMware vSphere 9.8, um die Performance von FlexGroup VMs mithilfe von ONTAP Kennzahlen (Dashboard- und VM-Berichte) zu überwachen und QoS auf einzelnen VMs zu managen. Diese Metriken sind derzeit nicht über ONTAP-Befehle oder APIs verfügbar.
* QoS (max./min. IOPS) kann auf einzelnen VMs oder auf allen VMs zu diesem Zeitpunkt in einem Datenspeicher festgelegt werden. Die Festlegung der QoS auf allen VMs ersetzt alle separaten Einstellungen pro VM. Einstellungen erweitern nicht auch künftig auf neue oder migrierte VMs. Sie können entweder QoS auf den neuen VMs festlegen oder QoS neu auf alle VMs im Datastore anwenden.
* Das SnapCenter Plug-in für VMware vSphere Version 4.4 unterstützt Backup und Recovery von VMs in einem FlexGroup-Datenspeicher auf dem primären Storage-System. Während SnapMirror manuell für die Replizierung einer FlexGroup auf ein sekundäres System verwendet werden kann, verwaltet SCV 4.4 die sekundären Kopien nicht.

