---
sidebar: sidebar 
permalink: vmware/vmware-srm-ontap-tools-features.html 
keywords: vmware, site, recovery manager, vsrm, vsphere, ipv6, support, rest, api, replication, ccols, spbm, srm, appliance based 
summary: Funktionen, Grenzen und VVols unterstützen mit ONTAP Tools. 
---
= Neue Funktionen mit VLSR/SRM und ONTAP Tools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Seit dem Übergang von der älteren virtuellen Appliance bieten ONTAP Tools zahlreiche neue Funktionen, höhere Limits und neue VVols Unterstützung.



[[latest-versions-of-vsphere-and-site-recovery-manager]]
== Aktuelle Versionen von vSphere und Site Recovery Manager

NetApp verbindet seit nahezu zwei Jahrzehnten eine enge Partnerschaft mit VMware und ist bestrebt, die neuesten Versionen so schnell wie möglich zu unterstützen. Überprüfen Sie stets die NetApp https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool (IMT)"^] auf die neuesten qualifizierten Softwarekombinationen.



[[support-for-ipv6]]
== IPv6 wird unterstützt

IPv6 wird jetzt mit folgenden Einschränkungen unterstützt:

* Nicht unterstützt mit SRM 8.2 (8.1, 8.3 und 8. 4 und höher werden unterstützt)
* Überprüfen Sie, https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Interoperabilitäts-Matrix-Tool (IMT)"^] ob die neuesten qualifizierten Versionen vorhanden sind.




[[greater-scale]]
== Besser skalieren

Die ONTAP-Tools 10.4 SRA unterstützen jetzt die maximale Skalierbarkeit von VLSR/SRM.

* Gesamtzahl der geschützten VMs = 5000
* Anzahl der VMs pro Schutzgruppe = 1000
* Gesamtzahl der Wiederherstellungspläne = 250
* Gesamtzahl der Schutzgruppen pro Wiederherstellungsplan = 250
* Gesamtzahl der replizierten Datenspeicher = 255
* Gesamtzahl der gleichzeitig laufenden Recovery-Pläne. = 10




[[synchronous-replication]]
== Synchrone Replizierung

Eine lang erwartete und viel erwartete neue Funktion ist SnapMirror Synchronous (SM-S) mit ONTAP 9.5 und höher, die eine granulare Band RPO Datenreplizierungslösung für Ihre geschäftskritischen Anwendungen liefert. SM-S erfordert ONTAP-Tools 9.8 oder höher.



[[rest-api-support]]
== REST-API-Unterstützung

Die SRA Serverkonfiguration kann jetzt durch REST-APIs gemanagt werden. Eine Swagger UI wurde hinzugefügt, um Sie bei der Erstellung Ihrer Automatisierungs-Workflows zu unterstützen. Sie finden sie auf Ihrer ONTAP Tools Appliance unter `https://<appliance>:8443/`.
