---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Kunden entscheiden sich aufgrund der Unified-SAN- und NAS-Storage-Lösungen und der neuen vereinfachten disaggregierten Storage-Architektur, die auch in den neuesten All-SAN-Arrays zu finden ist, sicher für ONTAP vSphere. Diese Plattform bietet einen außergewöhnlichen Snapshot-Schutz und leistungsstarke Management Tools. Durch das verlagern von Funktionen in dedizierten Storage maximiert ONTAP die Host-Ressourcen, senkt Kosten und sorgt für eine optimale Performance. Darüber hinaus können Workloads mit Storage vMotion problemlos über VMFS, NFS oder VVols migriert werden. 
---
= Warum ONTAP für VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Kunden entscheiden sich vertrauensvoll für ONTAP für vSphere sowohl für SAN- als auch für NAS-Speicherlösungen.  Die neue vereinfachte disaggregierte Speicherarchitektur, die in den neuesten All SAN Arrays enthalten ist, bietet SAN-Speicheradministratoren eine vereinfachte Erfahrung, die ihnen vertraut ist, während die meisten Integrationen und Funktionen herkömmlicher ONTAP -Systeme erhalten bleiben.  ONTAP -Systeme bieten außergewöhnlichen Snapshot-Schutz und robuste Verwaltungstools.  Durch die Auslagerung von Funktionen auf dedizierten Speicher maximiert ONTAP die Hostressourcen, senkt die Kosten und sorgt für optimale Leistung.  Darüber hinaus können Workloads mithilfe von Storage vMotion problemlos über VMFS, NFS oder vVols migriert werden.



== Die Vorteile der Verwendung von ONTAP für vSphere

Zehntausende Kunden haben sich für ONTAP als Storage-Lösung für vSphere entschieden. Dafür gibt es viele Gründe, beispielsweise ein Unified-Storage-System, das sowohl SAN- als auch NAS-Protokolle unterstützt, robuste Datensicherungsfunktionen mittels platzsparender Snapshots und eine Fülle von Tools, die Sie beim Management von Applikationsdaten unterstützen. Wenn Sie ein Storage-System getrennt vom Hypervisor verwenden, können Sie viele Funktionen verlagern und Ihre Investitionen in vSphere Host-Systeme optimal nutzen. Hierdurch wird sichergestellt, dass Ihre Host-Ressourcen schwerpunktmäßig für Applikations-Workloads verwendet werden. Darüber hinaus werden zufällige Auswirkungen auf die Performance von Applikationen aufgrund des Storage-Betriebs vermieden.

Die Verwendung von ONTAP zusammen mit vSphere ist eine großartige Kombination, mit der Sie die Kosten für Host-Hardware und VMware-Software senken können.  Sie können Ihre Daten außerdem zu geringeren Kosten bei gleichbleibend hoher Leistung schützen.  Da virtualisierte Workloads mobil sind, können Sie mithilfe von Storage vMotion verschiedene Ansätze erkunden, um VMs zwischen VMFS-, NFS- oder vVols Datenspeichern zu verschieben, und zwar alle auf demselben Speichersystem.

Hier sind die wichtigsten Faktoren, die Kunden heute schätzen:

* *Einheitlicher Speicher.*  Systeme, auf denen ONTAP läuft, sind in mehreren wichtigen Punkten vereinheitlicht.  Ursprünglich bezog sich dieser Ansatz sowohl auf NAS- als auch auf SAN-Protokolle, und ONTAP ist weiterhin eine führende Plattform für SAN, abgesehen von seiner ursprünglichen Stärke im NAS-Bereich.  In der vSphere-Welt könnte dieser Ansatz auch ein einheitliches System für die virtuelle Desktop-Infrastruktur (VDI) zusammen mit der virtuellen Server-Infrastruktur (VSI) bedeuten.  Systeme mit ONTAP sind für VSI in der Regel weniger teuer als herkömmliche Enterprise-Arrays und verfügen dennoch über erweiterte Speichereffizienzfunktionen, um VDI im selben System zu verarbeiten.  ONTAP vereint außerdem eine Vielzahl von Speichermedien, von SSDs bis SATA, und kann diese problemlos in die Cloud erweitern.  Es ist nicht erforderlich, ein Speicherbetriebssystem für die Leistung, ein anderes für Archive und noch ein weiteres für die Cloud zu kaufen.  ONTAP verbindet sie alle.
* *All-SAN-Array (ASA).* Die aktuellen ONTAP ASA Systeme (beginnend mit A1K, A90, A70, A50, A30 und A20) basieren auf einer neuen Storage-Architektur, mit der das herkömmliche ONTAP Storage-Paradigma beim Management von Aggregaten und Volumes entfällt. Da es keine Filesystem-Shares gibt, werden keine Volumes benötigt! Sämtlicher Storage, der mit einem HA-Paar verbunden ist, wird als gemeinsame Storage Availability Zone (SAZ) behandelt, in der LUNs und NVMe-Namespaces als „Storage Units“ (Sus) bereitgestellt werden. Die neuesten ASA Systeme sollen einfach zu managen sein und bieten SAN-Storage-Administratoren vertraute Erfahrung. Diese neue Architektur eignet sich ideal für vSphere Umgebungen, da sie das Management von Storage-Ressourcen vereinfacht und den SAN Storage-Administratoren eine vereinfachte Erfahrung bietet. Die ASA Architektur unterstützt darüber hinaus die neueste NVMe over Fabrics (NVMe-of) Technologie, die noch bessere Performance und Skalierbarkeit für vSphere Workloads bietet.
* *Snapshot-Technologie.* ONTAP ist der erste Anbieter von Snapshot-Technologie für die Datensicherung und bleibt auch in der Branche der fortschrittlichste Anbieter. Dieser platzsparende Ansatz für die Datensicherung wurde erweitert und unterstützt nun VMware vSphere APIs for Array Integration (VAAI). Dank dieser Integration können Sie die Snapshot-Funktionen von ONTAP für Backup- und Restore-Vorgänge nutzen und so die Auswirkungen auf Ihre Produktionsumgebung verringern. Dieser Ansatz ermöglicht zudem, Snapshots für die schnelle Wiederherstellung von VMs zu verwenden und so den Zeit- und Arbeitsaufwand für die Wiederherstellung von Daten zu reduzieren. Darüber hinaus ist die Snapshot-Technologie von ONTAP in die Live Site Recovery (VLSR, früher Site Recovery Manager [SRM])-Lösungen von VMware integriert. So erhalten Sie eine umfassende Datensicherungsstrategie für Ihre virtualisierte Umgebung.
* *Virtuelle Volumes und speicherrichtlinienbasierte Verwaltung.*  NetApp war einer der ersten Designpartner von VMware bei der Entwicklung von vSphere Virtual Volumes (vVols) und lieferte architektonischen Input und frühzeitigen Support für vVols und VMware vSphere APIs for Storage Awareness (VASA).  Dieser Ansatz ermöglichte nicht nur eine granulare VM-Speicherverwaltung für VMFS, sondern unterstützte auch die Automatisierung der Speicherbereitstellung durch eine auf Speicherrichtlinien basierende Verwaltung.  Dieser Ansatz ermöglicht es Speicherarchitekten, Speicherpools mit unterschiedlichen Funktionen zu entwerfen, die von VM-Administratoren problemlos genutzt werden können.  ONTAP ist in der Speicherbranche führend im vVol-Maßstab und unterstützt Hunderttausende von vVols in einem einzigen Cluster, während Anbieter von Enterprise-Arrays und kleineren Flash-Arrays nur einige Tausend vVols pro Array unterstützen.  NetApp treibt mit kommenden Funktionen auch die Entwicklung des granularen VM-Managements voran.
* *Speichereffizienz.*  Obwohl NetApp als erstes Unternehmen Deduplizierung für Produktions-Workloads bereitstellte, war diese Innovation weder die erste noch die letzte in diesem Bereich.  Es begann mit Snapshots, einem platzsparenden Datenschutzmechanismus ohne Leistungseinbußen, zusammen mit der FlexClone -Technologie zum sofortigen Erstellen von Lese-/Schreibkopien von VMs für die Produktion und Sicherung.  NetApp lieferte anschließend Inline-Funktionen, darunter Deduplizierung, Komprimierung und Zero-Block-Deduplizierung, um den größtmöglichen Speicherplatz aus teuren SSDs herauszuholen.  ONTAP hat außerdem die Möglichkeit hinzugefügt, kleinere E/A-Vorgänge und Dateien durch Komprimierung in einen Festplattenblock zu packen.  Durch die Kombination dieser Funktionen konnten Kunden im Allgemeinen Einsparungen von bis zu 5:1 bei VSI und bis zu 30:1 bei VDI erzielen.  Die neueste Generation von ONTAP -Systemen umfasst außerdem hardwarebeschleunigte Komprimierung und Deduplizierung, wodurch die Speichereffizienz weiter verbessert und die Kosten gesenkt werden können.  Mit diesem Ansatz können Sie mehr Daten auf weniger Speicherplatz speichern, wodurch die Gesamtkosten für die Speicherung gesenkt und die Leistung verbessert werden.  NetApp ist von seinen Speichereffizienzfunktionen so überzeugt, dass es einen Link anbietet:https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Effizienzgarantie^].
* *Mehrere Mandanten.*  ONTAP ist seit langem führend im Bereich Multitenancy und ermöglicht Ihnen die Erstellung mehrerer virtueller Speichermaschinen (SVMs) auf einem einzigen Cluster.  Mit diesem Ansatz können Sie Arbeitslasten isolieren und verschiedenen Mandanten unterschiedliche Servicelevel bereitstellen. Dies ist ideal für Dienstanbieter und große Unternehmen.  Die neueste Generation von ONTAP -Systemen umfasst auch Unterstützung für das Tenant-Kapazitätsmanagement.  Mit dieser Funktion können Sie Kapazitätsgrenzen für jeden Mandanten festlegen und so sicherstellen, dass kein einzelner Mandant alle verfügbaren Ressourcen verbrauchen kann.  Dieser Ansatz trägt dazu bei, dass alle Mieter das Serviceniveau erhalten, das sie erwarten, und bietet gleichzeitig ein hohes Maß an Sicherheit und Isolation zwischen den Mietern.  Darüber hinaus sind die Multitenancy-Funktionen von ONTAP in die vSphere-Plattform von VMware integriert, sodass Sie Ihre virtualisierte Umgebung einfach verwalten und überwachen können durch https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["ONTAP Tools für VMware vSphere"] Und https://docs.netapp.com/us-en/data-infrastructure-insights/["Einblicke In Die Dateninfrastruktur"] .
* *Hybrid Cloud.*  Ganz gleich, ob Sie die Lösung für eine lokale Private Cloud, eine Public Cloud-Infrastruktur oder eine Hybrid Cloud verwenden, die das Beste aus beiden kombiniert: ONTAP -Lösungen unterstützen Sie beim Aufbau Ihrer Datenstruktur, um die Datenverwaltung zu rationalisieren und zu optimieren.  Beginnen Sie mit leistungsstarken All-Flash-Systemen und koppeln Sie diese dann mit Festplatten- oder Cloud-Speichersystemen für Datenschutz und Cloud-Computing.  Wählen Sie zwischen Azure, AWS, IBM oder Google Cloud, um Kosten zu optimieren und Lock-in-Strategien zu vermeiden. Nutzen Sie bei Bedarf erweiterten Support für OpenStack und Container-Technologien.  NetApp bietet außerdem Cloud-basierte Backup- (SnapMirror Cloud, Cloud Backup Service und Cloud Sync) sowie Storage-Tiering- und Archivierungstools (FabricPool) für ONTAP an, um die Betriebskosten zu senken und die große Reichweite der Cloud zu nutzen.
* * Und mehr.* Nutzen Sie die extreme Performance von NetApp AFF A-Series Arrays, um Ihre virtualisierte Infrastruktur zu beschleunigen und gleichzeitig die Kosten im Griff zu haben. Mit horizontal skalierbaren ONTAP Clustern profitieren Sie bei der Wartung, bei Upgrades und selbst beim kompletten Ersatz Ihres Storage-Systems von einem durchgängig unterbrechungsfreien Betrieb. Daten im Ruhezustand werden mit NetApp Verschlüsselungsfunktionen ohne zusätzliche Kosten geschützt. Durch fein abgestimmte Quality-of-Service- Funktionen stellen Sie sicher, dass die Performance den geschäftlichen Service-Levels entspricht. Sie alle sind Bestandteil des umfangreichen Funktionsbereichs, das in ONTAP, der branchenführenden Software für das Enterprise-Datenmanagement, enthalten ist.

