---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Kunden entscheiden sich aufgrund der Unified-SAN- und NAS-Storage-Lösungen und der neuen vereinfachten disaggregierten Storage-Architektur, die auch in den neuesten All-SAN-Arrays zu finden ist, sicher für ONTAP vSphere. Diese Plattform bietet einen außergewöhnlichen Snapshot-Schutz und leistungsstarke Management Tools. Durch das verlagern von Funktionen in dedizierten Storage maximiert ONTAP die Host-Ressourcen, senkt Kosten und sorgt für eine optimale Performance. Darüber hinaus können Workloads mit Storage vMotion problemlos über VMFS, NFS oder VVols migriert werden. 
---
= Warum ONTAP für VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Kunden entscheiden sich bei SAN- und NAS-Storage-Lösungen sicher für ONTAP für vSphere.die neue vereinfachte disaggregierte Storage-Architektur, die in den neuesten rein SAN-basierten Arrays enthalten ist, bietet SAN-Storage-Administratoren die vereinfachte Erfahrung, wobei die meisten Integrationen und Funktionen herkömmlicher ONTAP-Systeme erhalten bleiben. ONTAP-Systeme bieten einen hervorragenden Snapshot-Schutz und solide Management-Tools. Durch das verlagern von Funktionen in dedizierten Storage maximiert ONTAP die Host-Ressourcen, senkt Kosten und sorgt für eine optimale Performance. Darüber hinaus können Workloads mit Storage vMotion problemlos über VMFS, NFS oder VVols migriert werden.



== Die Vorteile der Verwendung von ONTAP für vSphere

Zehntausende Kunden haben sich für ONTAP als Storage-Lösung für vSphere entschieden. Dafür gibt es viele Gründe, beispielsweise ein Unified-Storage-System, das sowohl SAN- als auch NAS-Protokolle unterstützt, robuste Datensicherungsfunktionen mittels platzsparender Snapshots und eine Fülle von Tools, die Sie beim Management von Applikationsdaten unterstützen. Wenn Sie ein Storage-System getrennt vom Hypervisor verwenden, können Sie viele Funktionen verlagern und Ihre Investitionen in vSphere Host-Systeme optimal nutzen. Hierdurch wird sichergestellt, dass Ihre Host-Ressourcen schwerpunktmäßig für Applikations-Workloads verwendet werden. Darüber hinaus werden zufällige Auswirkungen auf die Performance von Applikationen aufgrund des Storage-Betriebs vermieden.

Die Kombination von ONTAP und vSphere ermöglicht Kosteneinsparungen für Host-Hardware und VMware Software. Schützen Sie Ihre Daten außerdem zu geringeren Kosten mit konstant hoher Performance. Da virtualisierte Workloads mobil sind, können Sie mit Storage vMotion verschiedene Ansätze nutzen, um VMs auf VMFS-, NFS- oder VVols-Datastores zu verschieben. Und das alles auf ein und demselben Storage-System.

Im Folgenden sind wichtige Faktoren aufgeführt, die heutzutage von Kunden wertvoll sind:

* *Unified Storage.* Systeme mit ONTAP werden auf unterschiedliche Weise vereinheitlicht. Dieser Ansatz bezog sich ursprünglich auf NAS- und SAN-Protokolle. ONTAP ist dabei weiterhin eine der führenden Plattformen für SAN und bietet in Bezug auf NAS die ursprünglichen Stärken. Bei vSphere könnte dieser Ansatz auch für ein einheitliches System für Virtual Desktop Infrastructure (VDI) in Kombination mit einer virtuellen Serverinfrastruktur (VSI) stehen. Systeme mit ONTAP sind bei VSI in der Regel kostengünstiger als herkömmliche Enterprise-Arrays, bieten gleichzeitig aber fortschrittliche Storage-Effizienzfunktionen, mit denen Sie im selben System auch VDI gerecht werden können. ONTAP vereint außerdem eine Reihe von Storage-Medien – von SSDs bis SATA – und kann diese problemlos in die Cloud erweitern. Es müssen nicht ein Storage-Betriebssystem für Performance, ein anderes für Archive und noch ein weiteres für die Cloud erworben werden. Sie alle sind in ONTAP integriert.
* *All-SAN-Array (ASA).* Die aktuellen ONTAP ASA Systeme (beginnend mit A1K, A90, A70, A50, A30 und A20) basieren auf einer neuen Storage-Architektur, mit der das herkömmliche ONTAP Storage-Paradigma beim Management von Aggregaten und Volumes entfällt. Da es keine Filesystem-Shares gibt, werden keine Volumes benötigt! Sämtlicher Storage, der mit einem HA-Paar verbunden ist, wird als gemeinsame Storage Availability Zone (SAZ) behandelt, in der LUNs und NVMe-Namespaces als „Storage Units“ (Sus) bereitgestellt werden. Die neuesten ASA Systeme sollen einfach zu managen sein und bieten SAN-Storage-Administratoren vertraute Erfahrung. Diese neue Architektur eignet sich ideal für vSphere Umgebungen, da sie das Management von Storage-Ressourcen vereinfacht und den SAN Storage-Administratoren eine vereinfachte Erfahrung bietet. Die ASA Architektur unterstützt darüber hinaus die neueste NVMe over Fabrics (NVMe-of) Technologie, die noch bessere Performance und Skalierbarkeit für vSphere Workloads bietet.
* *Snapshot-Technologie.* ONTAP ist der erste Anbieter von Snapshot-Technologie für die Datensicherung und bleibt auch in der Branche der fortschrittlichste Anbieter. Dieser platzsparende Ansatz für die Datensicherung wurde erweitert und unterstützt nun VMware vSphere APIs for Array Integration (VAAI). Dank dieser Integration können Sie die Snapshot-Funktionen von ONTAP für Backup- und Restore-Vorgänge nutzen und so die Auswirkungen auf Ihre Produktionsumgebung verringern. Dieser Ansatz ermöglicht zudem, Snapshots für die schnelle Wiederherstellung von VMs zu verwenden und so den Zeit- und Arbeitsaufwand für die Wiederherstellung von Daten zu reduzieren. Darüber hinaus ist die Snapshot-Technologie von ONTAP in die Live Site Recovery (VLSR, früher Site Recovery Manager [SRM])-Lösungen von VMware integriert. So erhalten Sie eine umfassende Datensicherungsstrategie für Ihre virtualisierte Umgebung.
* *Virtuelle Volumes und Policy-basiertes Storage-Management.* NetApp war schon früh als Design-Partner von VMware an der Entwicklung von vSphere Virtual Volumes (VVols) beteiligt und stellte architekturspezifischen Input und frühzeitig Unterstützung für VVols und VMware vSphere APIs for Storage Awareness (VASA) bereit. Durch diesen Ansatz wurde nicht nur das granulare VM-Storage-Management in VMFS integriert, sondern auch die Automatisierung der Storage-Bereitstellung durch richtlinienbasiertes Management unterstützt. Storage-Architekten können mit diesem Ansatz Storage-Pools mit unterschiedlichen Funktionen entwerfen, die von VM-Administratoren einfach genutzt werden können. ONTAP ist einer der führenden Anbieter von vVol Storage-Lösungen in der Storage-Branche, da es Hunderttausende VVols in einem einzigen Cluster unterstützt. Anbieter von Enterprise-Arrays und kleineren Flash-Arrays hingegen unterstützen gerade einmal mehrere Tausend VVols pro Array. Zudem bringt NetApp mit neuen Funktionen die Weiterentwicklung des granularen VM-Managements voran.
* *Storage-Effizienz.* NetApp stellte als erster Anbieter die Deduplizierung für Produktions-Workloads bereit, allerdings war diese Innovation weder die erste noch die letzte in diesem Bereich. Es begann mit Snapshots, einem platzsparenden Datensicherungsmechanismus ohne Auswirkungen auf die Performance, sowie mit FlexClone Technologie, bei der sofort Lese-/Schreibkopien von VMs für die Produktion und die Nutzung von Backups erstellt werden können. Danach stellte NetApp Inline-Funktionen bereit, darunter Deduplizierung, Komprimierung und Zero-Block-Deduplizierung, mit denen sich der Storage kostspieliger SSDs maximal ausschöpfen lässt. ONTAP ergänzte zudem die Möglichkeit, kleinere I/O-Vorgänge und Dateien durch Data-Compaction in einen Festplattenblock zu packen. Dank der Kombination dieser Funktionen verzeichnen Kunden in der Regel Einsparungen von bis zu 5:1 für VSI und von bis zu 30:1 für VDI. Die neueste Generation von ONTAP Systemen umfasst außerdem Hardware-beschleunigte Komprimierung und Deduplizierung, wodurch die Storage-Effizienz weiter verbessert und die Kosten gesenkt werden können. Durch diesen Ansatz können Sie mehr Daten platzsparend speichern, wodurch sich die Storage-Gesamtkosten senken und die Performance verbessern lassen. NetApp ist so überzeugt von seiner Storage-Effizienz-Funktionalität, dass sie einen Link:https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Effizienz-Garantie^] bietet.
* *Multimandanten.* ONTAP ist seit langem einer der führenden Anbieter für Mandantenfähigkeit und ermöglicht Ihnen das Erstellen mehrerer Storage Virtual Machines (SVMs) in einem einzelnen Cluster. Dieser Ansatz ermöglicht die Isolierung von Workloads und die Bereitstellung verschiedener Service-Level für verschiedene Mandanten, wodurch sich diese Lösung ideal für Service-Provider und Großunternehmen eignet. Die neueste Generation von ONTAP Systemen bietet zudem Unterstützung für ein tendentiges Kapazitätsmanagement. Durch diese Funktion können Sie für jeden Mandanten Kapazitätsgrenzen festlegen, sodass kein einzelner Mandant alle verfügbaren Ressourcen in Anspruch nehmen kann. Durch diesen Ansatz wird sichergestellt, dass alle Mandanten den erwarteten Service erhalten. Gleichzeitig bietet dieser Ansatz einen hohen Grad an Sicherheit und Isolation zwischen Mandanten. Darüber hinaus sind die ONTAP Funktionen für Mandantenfähigkeit in die VMware vSphere Plattform integriert, sodass Sie Ihre virtualisierte Umgebung über und einfach managen und https://docs.netapp.com/us-en/data-infrastructure-insights/["Einblicke In Die Dateninfrastruktur"] überwachen https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["ONTAP Tools für VMware vSphere"] können.
* *Hybrid Cloud.* ob in der Private Cloud vor Ort, in einer Public-Cloud-Infrastruktur oder in einer Hybrid Cloud, die das Beste der beiden Lösungen vereint – ONTAP Lösungen helfen Ihnen, Ihre Data Fabric zur Optimierung und zum Optimieren des Datenmanagements aufzubauen. Den Anfang machen hochperformante All-Flash-Systeme, die dann für die Datensicherung und das Cloud-Computing mit Festplatten- oder Cloud-Storage-Systemen gekoppelt werden. Zur Kostenoptimierung und Vermeidung einer Anbieterbindung stehen hierbei Azure, AWS, IBM oder Google Clouds zur Auswahl. Bei Bedarf kann die erweiterte Unterstützung für OpenStack und Containertechnologien genutzt werden. NetApp bietet darüber hinaus Cloud-basiertes Tiering und Archivierungstools (SnapMirror Cloud, Cloud Backup Service und Cloud Sync) sowie Storage-Systeme (FabricPool) für ONTAP, um die Betriebskosten zu senken und die große Reichweite der Cloud auszuschöpfen.
* * Und mehr.* Nutzen Sie die extreme Performance von NetApp AFF A-Series Arrays, um Ihre virtualisierte Infrastruktur zu beschleunigen und gleichzeitig die Kosten im Griff zu haben. Mit horizontal skalierbaren ONTAP Clustern profitieren Sie bei der Wartung, bei Upgrades und selbst beim kompletten Ersatz Ihres Storage-Systems von einem durchgängig unterbrechungsfreien Betrieb. Daten im Ruhezustand werden mit NetApp Verschlüsselungsfunktionen ohne zusätzliche Kosten geschützt. Durch fein abgestimmte Quality-of-Service- Funktionen stellen Sie sicher, dass die Performance den geschäftlichen Service-Levels entspricht. Sie alle sind Bestandteil des umfangreichen Funktionsbereichs, das in ONTAP, der branchenführenden Software für das Enterprise-Datenmanagement, enthalten ist.

