---
sidebar: sidebar 
permalink: oracle/dp/overview-dr.html 
keywords: oracle, database, ontap 
summary: NetApp ONTAP ist eine leistungsstarke Datenmanagementplattform mit nativen Funktionen, die u. a. sofortige Backup-, Restore- und Klonfunktionen, Effizienzfunktionen wie Inline-Komprimierung, unterbrechungsfreie Hardware-Upgrades und die Möglichkeit zum Import einer LUN aus einem fremden Storage Array umfasst. 
---
= Disaster Recovery mit Oracle
:allow-uri-read: 


[role="lead"]
NetApp MetroCluster bietet eine hochverfügbare Lösung ohne Datenverlust für geschäftskritische Oracle Workloads.

Zusätzlich vereinfachen integrierte Lösungen wie MetroCluster die komplizierte, horizontal skalierbare Oracle Datenbank, Applikation und Virtualisierungsinfrastrukturen von heute. MetroCluster ersetzt mehrere externe Datensicherungsprodukte und -Strategien durch ein einfaches, zentrales Storage Array. Sie bietet integriertes Backup, Recovery, Disaster Recovery und Hochverfügbarkeit (HA) innerhalb eines einzigen geclusterten Storage-Systems.


NOTE: Diese Dokumentation ersetzt den zuvor veröffentlichten technischen Bericht _TR-4592: Oracle on MetroCluster._
