---
sidebar: sidebar 
permalink: mysql/mysql-overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: MySQL auf ONTAP 
---
= MySQL-Datenbanken auf ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL und seine Varianten, darunter MariaDB und Percona MySQL, ist die weltweit beliebteste Datenbank.


NOTE: Diese Dokumentation zu ONTAP und der MySQL-Datenbank ersetzt die zuvor veröffentlichte _TR-4722: MySQL-Datenbank unter NetApp ONTAP Best Practices._

Zu den Merkmalen von MySQL gehören:

* *Lower TCO.* MySQL ist ein leistungsfähiges, kostenloses Open-Source-Datenbankmanagementsystem, das seit Jahren verfügbar ist. Sie ist sehr stabil. Es hat Community-Unterstützung, die Pflege, Debuggen und neue Funktionen hinzufügen hilft. Wenn eine Webanwendung mehr als eine Datenbank benötigt oder einen Lastausgleich oder eine gemeinsame Nutzung erfordert, können Sie Datenbankinstanzen einfach nur mit Hardwarekosten einrichten, anstatt kommerzielle Datenbanken, die für jede Instanz eine einzelne Lizenz benötigen.
* *Zuverlässigkeit, Leistung und Benutzerfreundlichkeit.* eines der Merkmale von MySQL ist die außergewöhnliche Leistung und Skalierbarkeit, weshalb so viele webbasierte Unternehmen es nutzen. MySQL nutzt mehrere wichtige Stärken, um eine schnelle Performance zu liefern. Da der Wettbewerb immer nur einen Mausklick (oder Touchscreen) entfernt ist, sind schnelle Antworten auf Kundenanfragen und -Aktivitäten von größter Bedeutung. Die Datenbank, die webbasierte Applikationen bereitstellt, muss sowohl bei Lese- (einfachen als auch bei komplexen Abfragen) als auch bei Schreibvorgängen eine extrem hohe Performance bieten.
* *Datenbankentwicklung, -Design und -Administration.* MySQL Workbench bietet eine integrierte Entwicklungs-, Design- und Administrationsumgebung, um Entwickler und DBAs produktiver zu machen. Verschiedene Entwickler suchen nach verschiedenen Funktionen in einer Datenbank, und MySQL bietet eine Reihe von Funktionen. Es kann sowohl auf einem Laptop als auch auf einem Desktop-PC angemessen ausgeführt werden. Die IT-Abteilung kann sich leicht an die Umgebung anpassen und so sicherstellen, dass sie nicht mit vorhandenen Webservern oder Anwendungen kollidiert.
* *Umfassende Transaktionsunterstützung.* MySQL ist eine der robustesten transaktionalen Datenbankengines auf dem Markt. Es ist die Lösung für vollständige Datenintegrität und bietet Funktionen wie vollständige atomare, konsistente, isolierte, dauerhafte Transaktionsunterstützung; Unterstützung von Multiversionstransaktionen; und uneingeschränkte Verriegelung auf Zeilenebene. Sie ermöglicht die sofortige Deadlock-Identifizierung durch servererzwungene referenzielle Integrität.
* *Datensicherheit.* MySQL ist weltweit bekannt als das sicherste und zuverlässigste Datenbankmanagementsystem, das in gängigen Web-Anwendungen wie WordPress, Drupal, Joomla, Facebook, Google, und Twitter. Die Datensicherheit und Unterstützung für die Transaktionsverarbeitung, die mit der aktuellen Version von MySQL einhergehen, kann jedem Unternehmen zugute kommen, insbesondere E-Commerce-Unternehmen, die häufig Geldtransfers durchführen.
* *Pluggable Architecture.* die Architektur der MySQL-Speicherengine ermöglicht es einem Datenbankexperten, eine spezielle Speicherengine für eine bestimmte Anwendung auszuwählen, ohne die Codierungsanforderungen für Anwendungen verwalten zu müssen. Die MySQL Server-Architektur isoliert Applikationsprogrammierer und DBA von allen Details der Low-Level-Implementierung auf Storage-Ebene und bietet so ein konsistentes und einfaches Applikationsmodell sowie eine API. Obwohl verschiedene Funktionen in verschiedenen Storage Engines verwendet werden, ist die Applikation von diesen Unterschieden abgeschirmt.


Die effiziente und modulare MySQL Architektur bietet enorme Vorteile, wenn Sie sich auf eine bestimmte Applikationsanforderungen – wie Data Warehousing, Transaktionsverarbeitung oder HA-Situationen – konzentrieren möchten, während Sie Schnittstellen und Services nutzen, die unabhängig von einer einzelnen Storage Engine sind.
