---
sidebar: sidebar 
permalink: mysql/mysql-innodb_buffer_pool_size.html 
keywords: MySQL,MariaDB,innodb_buffer_pool_size 
summary: MySQL auf ONTAP 
---
= innodb_Buffer_Pool_size
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der InnoDB Pufferpool ist der wichtigste Teil jeder Tuning-Aktivität.

InnoDB setzt stark auf den Pufferpool für das Caching von Indizes und Rudern der Daten, den adaptiven Hash-Index, den Insert-Puffer und viele andere interne Datenstrukturen. Der Puffer-Pool puffert Änderungen an Daten, damit Schreibzugriffe nicht sofort in den Storage übernommen werden müssen, was die Performance verbessert. Der Pufferpool ist integraler Bestandteil von InnoDB und muss entsprechend angepasst werden. Berücksichtigen Sie beim Festlegen der Größe des Puffer-Pools die folgenden Faktoren:

* Stellen Sie für eine dedizierte InnoDB-Maschine die Pufferpoolgröße auf 80 % oder mehr verfügbaren RAM ein.
* Wenn es sich nicht um einen dedizierten MySQL-Server handelt, stellen Sie die Größe auf 50 % des RAM ein.

