---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/mc-mcc-nvfail.html 
keywords: oracle, metrocluster, extended rac, rac, nvfail, switchover 
summary: Oracle auf MetroCluster - NVFAIL 
---
= MetroCluster und NVFAIL
:allow-uri-read: 


[role="lead"]
NVFAIL ist eine allgemeine Datenintegritätsfunktion in ONTAP, die für den Datenbank-Workload besonders wichtig ist und wird in ausführlicher behandelt link:../ontap-configuration/oracle_and_nvfail.html["NV-FEHLER"]. Für NVFAIL gibt es auch MetroCluster-spezifische Überlegungen.



== Erweiterter RAC mit manuell erzwungenem NVFAIL

Die sicherste Option, um eine Umschaltung mit einem erweiterten RAC-Cluster zu erzwingen, ist die Angabe `-force-nvfail-all` An der Kommandozeile. Diese Option ist als Notfallmaßnahme verfügbar, um sicherzustellen, dass alle zwischengespeicherten Daten gelöscht werden. Wenn ein Host Speicherressourcen verwendet, die sich ursprünglich am Standort mit Notfällen befinden, erhält er entweder I/O-Fehler oder eine veraltete Dateihandle (`ESTALE`) Fehler. Oracle Datenbanken stürzt ab, und Dateisysteme werden entweder vollständig offline geschaltet oder in den schreibgeschützten Modus gewechselt.

Nachdem die Umschaltung abgeschlossen ist, wird der angezeigt `in-nvfailed-state` Flag muss gelöscht werden und die LUNs müssen in den Online-Modus versetzt werden. Nach Abschluss dieser Aktivität kann die Datenbank neu gestartet werden. Diese Aufgaben können automatisiert werden, um die RTO zu reduzieren.



== Erweiterter RAC mit dr-Force-nvfail

Die sicherste Konfiguration ist die Einstellung `dr-force-nvfail` Markieren Sie auf allen Volumes, auf die von einem Remote-Standort aus zugegriffen werden kann. Daher stehen die Volumes beim Betreten nicht mehr zur Verfügung `in-nvfailed-state` Während einer Umschaltung. Nachdem die Umschaltung abgeschlossen ist, wird der angezeigt `in-nvfailed-state` Flag muss gelöscht und die LUNs müssen in den Online-Modus versetzt werden. Nach Abschluss dieser Aktivitäten kann die Datenbank neu gestartet werden. Diese Aufgaben können automatisiert werden, um die RTO zu reduzieren.

Das Ergebnis ähnelt der Verwendung von `-force-nvfail-all` Flagge. Die Anzahl der betroffenen Volumes kann jedoch auf die Volumes beschränkt werden, die vor Anwendungen oder Betriebssystemen mit veralteten Caches geschützt werden müssen.



== Erweiterter RAC ohne dr-Force-nvfail

Es gibt zwei entscheidende Anforderungen an eine Umgebung, die nicht verwendet wird `dr-force-nvfail` Auf Datenbank-Volumes:

* Ein erzwungenes Switchover darf nicht mehr als 30 Sekunden nach dem Ausfall des primären Standorts erfolgen.
* Eine Umschaltung darf nicht während Wartungsarbeiten oder unter anderen Bedingungen erfolgen, bei denen SyncMirror Plexe oder NVRAM-Replizierung nicht synchron sind. Die erste Anforderung kann mithilfe der Tiebreaker Software erfüllt werden, die so konfiguriert ist, dass nach einem Standortausfall innerhalb von 30 Sekunden eine Umschaltung durchgeführt wird. Dies bedeutet jedoch nicht, dass die Umschaltung innerhalb von 30 Sekunden nach Erkennung eines Standortausfalls durchgeführt werden muss. Das bedeutet, dass es nicht mehr sicher ist, eine Umschaltung zu erzwingen, wenn 30 Sekunden vergangen sind, seit die Betriebsbereitschaft eines Standorts bestätigt wurde.


Die zweite Anforderung wird teilweise erfüllt, indem alle Funktionen zum automatisierten Switchover deaktiviert werden, wenn bekannt ist, dass die MetroCluster-Konfiguration nicht synchron ist. Eine bessere Option ist die Nutzung einer Tiebreaker Lösung, mit der der Systemzustand der NVRAM-Replizierung und der SyncMirror Plexe überwacht werden kann. Wenn das Cluster nicht vollständig synchronisiert ist, sollte Tiebreaker keine Umschaltung auslösen.

Die NetApp-MCTB-Software kann den Synchronisierungsstatus nicht überwachen, daher sollte sie deaktiviert werden, wenn MetroCluster aus irgendeinem Grund nicht synchron ist. ClusterLion verfügt über Funktionen zur NVRAM-Überwachung und Plex-Überwachung und kann so konfiguriert werden, dass das Switchover nur ausgelöst wird, wenn für das MetroCluster-System eine vollständige Synchronisierung bestätigt wurde.
