---
sidebar: sidebar 
permalink: postgres/postgres-overview.html 
keywords: PostgreSQL,database,postgres 
summary: PostgreSQL-Datenbanken auf ONTAP 
---
= PostgreSQL-Datenbanken auf ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
PostgreSQL wird mit Varianten wie PostgreSQL, PostgreSQL Plus und EDB Postgres Advanced Server (EPAS) geliefert. PostgreSQL wird typischerweise als Back-End-Datenbank für Multi-Tier-Applikationen implementiert. Es wird von gängigen Middleware-Paketen (wie PHP, Java, Python, Tcl/TK, ODBC, Und JDBC) und war in der Vergangenheit eine beliebte Wahl für Open-Source-Datenbankmanagementsysteme. NetApp ONTAP ist eine ausgezeichnete Wahl für die Ausführung von PostgreSQL-Datenbanken aufgrund seiner Zuverlässigkeit, seiner hohen Performance und seiner effizienten Datenmanagementfunktionen.


NOTE: Diese Dokumentation zu ONTAP und der PostgreSQL-Datenbank ersetzt die zuvor veröffentlichte _TR-4770: PostgreSQL-Datenbank unter ONTAP Best Practices._

Mit dem exponentiellen Datenwachstum wird das Datenmanagement für Unternehmen komplexer. Dadurch steigen die Lizenz-, Betriebs-, Support- und Wartungskosten. Zur Senkung der Gesamtbetriebskosten empfiehlt sich der Wechsel von kommerziellen zu Open-Source-Datenbanken mit zuverlässigem, leistungsstarkem Back-End Storage. PostgreSQL ist eine fortschrittliche Open-Source-Datenbank, die in akademischen, kommerziellen und großen Unternehmen weit verbreitet ist. Es kommt mit einem neuen Satz von Funktionen, die Lücken in anderen relationalen Datenbank-Management-Systemen (RDBMSs) zu adressieren.


NOTE: NetApp Kunden, die PostgreSQL-Datenbanken in physischen oder virtualisierten Umgebungen verwenden, können von den Best Practices für die erfolgreiche Implementierung und das Management von PostgreSQL-Datenbanken auf ONTAP profitieren. Die Empfehlungen sind allgemein gehalten, sodass sie nicht konfigurationsspezifisch sind. Abhängig von Ihren Geschäftsanforderungen können einige Vorschläge Änderungen erfordern. Sie müssen Ihre Umgebung mit der offiziellen Dokumentation für PostgreSQL, Hypervisoren, Betriebssysteme und ONTAP Storage vergleichen.
